/**
 * Ada 2022 emitter.
 *
 * Ada has no forward references across a package, so the model types are
 * emitted in dependency order (the spec's type graph is acyclic). Optional
 * properties are rendered as a `Has_X` flag next to `X`, which keeps every
 * record default-initialisable and avoids a generic Option type per model.
 */
import { sdkVersion, type GeneratedFile } from '../index.ts';
import { assertSupportedBody } from '../ir.ts';
import type { EnumType, Group, NamedType, ObjectType, Operation, Param, Spec, TypeRef } from '../ir.ts';
import { adaIdent, adaName } from '../naming.ts';

/** Body encodings this emitter can render. */
const SUPPORTED_BODIES = ['json', 'multipart', 'binary', 'text'] as const;
import { Writer } from '../writer.ts';

const HEADER = '--  Code generated by @uarp/codegen from spec/openapi.json. DO NOT EDIT.';
const ROOT = 'src/generated';

export function emitAda(spec: Spec): GeneratedFile[] {
  for (const group of spec.groups) {
    for (const op of group.operations) assertSupportedBody(op, [...SUPPORTED_BODIES]);
  }
  const ordered = sortByDependency(spec.types);
  const arrayElements = collectArrayElements(spec);
  const files: GeneratedFile[] = [];

  files.push({ path: `${ROOT}/uarp-meta.ads`, content: emitMeta(spec) });
  files.push({ path: `${ROOT}/uarp-models.ads`, content: emitModelsSpec(spec, ordered, arrayElements) });
  files.push({ path: `${ROOT}/uarp-models.adb`, content: emitModelsBody(ordered) });
  files.push({ path: `${ROOT}/uarp-api.ads`, content: emitApiParent(spec) });
  for (const group of spec.groups) {
    const unit = `uarp-api-${adaName(group.name).toLowerCase()}`;
    const spec_ = emitGroupSpec(group);
    files.push({ path: `${ROOT}/${unit}.ads`, content: spec_ });
    files.push({ path: `${ROOT}/${unit}.adb`, content: emitGroupBody(group, withClausesOf(spec_)) });
  }
  return files;
}

// -------------------------------------------------------------------- names

function typeName(name: string): string {
  return adaName(name);
}

function vectorName(name: string): string {
  return `${typeName(name)}_Vectors`;
}

function enumKindType(name: string): string {
  return `${typeName(name)}_Kind`;
}

function enumLiteral(typeText: string, value: string): string {
  const suffix = adaName(value) || 'Empty';
  return adaIdent(`${typeText}_${/^[0-9]/.test(suffix) ? 'N_' + suffix : suffix}`);
}

// --------------------------------------------------------------------- meta

function emitMeta(spec: Spec): string {
  const w = new Writer('   ');
  w.line(HEADER);
  w.line();
  w.line('package UARP.Meta is');
  w.indent(() => {
    w.line();
    w.line('--  Version of the OpenAPI document this SDK was generated from.');
    w.line(`Spec_Version : constant String := "${escape(spec.version)}";`);
    w.line();
    w.line('--  Version of this SDK.');
    w.line(`SDK_Version : constant String := "${escape(sdkVersion())}";`);
    w.line();
    w.line('--  Production base URL.');
    w.line(`Default_Base_URL : constant String := "${escape(spec.servers[0]?.url ?? 'https://api.snaga.ai')}";`);
    w.line();
    w.line('--  Number of scopes the security scheme defines.');
    w.line(`Scope_Count : constant := ${spec.scopes.length};`);
    w.line();
    w.line('type Scope_Index is range 1 .. Scope_Count;');
    w.line('type Scope_Names is array (Scope_Index) of access constant String;');
    w.line();
    for (const [index, scope] of spec.scopes.entries()) {
      w.line(`Scope_${index + 1} : aliased constant String := "${escape(scope)}";`);
    }
    w.line();
    w.line('--  Every scope named by the UARP security scheme.');
    w.line('Scopes : constant Scope_Names :=');
    w.indent(() => {
      const entries = spec.scopes.map((_, index) => `Scope_${index + 1}'Access`);
      w.line(`(${entries.join(',\n    ')});`);
    });
    w.line();
  });
  w.line('end UARP.Meta;');
  return w.toString();
}

// ------------------------------------------------------------------ models

function emitModelsSpec(spec: Spec, ordered: NamedType[], arrayElements: Set<string>): string {
  const w = new Writer('   ');
  w.line(HEADER);
  w.line('--');
  w.line('--  Data models. Optional properties carry a `Has_` flag beside the value,');
  w.line('--  so every record can be default-initialised and compared with `=`.');
  w.line();
  w.line('with Ada.Containers.Vectors;');
  w.line();
  w.line('with UARP.JSON_Support;');
  w.line('with UARP.Types;');
  w.line();
  w.line('package UARP.Models is');
  w.indent(() => {
    w.line();
    w.line('use UARP.Types;');
    w.line();
    w.line('subtype JSON_Value is UARP.JSON_Support.JSON_Value;');
    w.line();

    for (const type of ordered) {
      if (type.kind === 'enum') emitEnumSpec(w, type);
      else if (type.kind === 'object') emitRecordSpec(w, type);
      else {
        comment(w, type.description);
        w.line(`subtype ${typeName(type.name)} is ${adaType(type.target)};`);
        w.line();
      }
      if (arrayElements.has(type.name)) {
        w.line(`package ${vectorName(type.name)} is new Ada.Containers.Vectors`);
        w.line(`  (Index_Type => Positive, Element_Type => ${typeName(type.name)});`);
        w.line();
      }
    }
  });
  w.line('end UARP.Models;');
  return w.toString();
}

function emitEnumSpec(w: Writer, type: EnumType): void {
  const name = typeName(type.name);
  const kind = enumKindType(type.name);
  const literals = enumLiterals(type);

  comment(w, type.description ?? `Values of \`${type.name}\`.`);
  w.line(`--  A value the API introduces later decodes as ${literals.unrecognized}`);
  w.line('--  with the original text kept in Raw.');
  w.line(`type ${kind} is`);
  w.line(`  (${[...literals.entries.map((e) => e.literal), literals.unrecognized].join(',\n   ')});`);
  w.line();
  w.line(`type ${name} is record`);
  w.indent(() => {
    w.line(`Kind : ${kind} := ${literals.unrecognized};`);
    w.line('Raw  : Text := Empty_Text;');
  });
  w.line('end record;');
  w.line();
  w.line(`function To_${name} (Value : String) return ${name};`);
  w.line(`function To_${name} (Kind : ${kind}) return ${name};`);
  w.line(`function Image (Model : ${name}) return String;`);
  w.line(`function To_JSON (Model : ${name}) return UARP.JSON_Support.JSON_Value;`);
  w.line(`function From_JSON (Node : UARP.JSON_Support.JSON_Value) return ${name};`);
  w.line();
}

interface EnumLiterals {
  entries: Array<{ literal: string; wire: string }>;
  unrecognized: string;
}

function enumLiterals(type: EnumType): EnumLiterals {
  const name = typeName(type.name);
  const used = new Set<string>();
  const entries = type.values.map((wire) => {
    let literal = enumLiteral(name, wire);
    while (used.has(literal)) literal += '_X';
    used.add(literal);
    return { literal, wire };
  });
  let unrecognized = `${name}_Unrecognized`;
  while (used.has(unrecognized)) unrecognized += '_X';
  return { entries, unrecognized };
}

function emitRecordSpec(w: Writer, type: ObjectType): void {
  const name = typeName(type.name);
  const fields = fieldsOf(type);

  comment(w, type.description ?? `\`${type.name}\` model.`);
  if (fields.length === 0) {
    w.line(`type ${name} is null record;`);
  } else {
    w.line(`type ${name} is record`);
    w.indent(() => {
      for (const field of fields) {
        comment(w, field.description);
        if (field.optional) w.line(`${field.has} : Boolean := False;`);
        w.line(`${field.name} : ${field.type}${field.initialiser};`);
      }
      if (type.additional) {
        w.line('--  Properties the server returned that this SDK does not model.');
        w.line('Extra : JSON_Value := UARP.JSON_Support.Null_Value;');
      }
    });
    w.line('end record;');
  }
  w.line();
  w.line(`function To_JSON (Model : ${name}) return UARP.JSON_Support.JSON_Value;`);
  w.line(`function From_JSON (Node : UARP.JSON_Support.JSON_Value) return ${name};`);
  w.line();
}

interface Field {
  name: string;
  has: string;
  type: string;
  initialiser: string;
  optional: boolean;
  wire: string;
  ref: TypeRef;
  description?: string;
}

function fieldsOf(type: ObjectType): Field[] {
  const used = new Set<string>();
  return type.properties.map((prop) => {
    let base = adaName(prop.wire) || 'Value';
    if (/^[0-9]/.test(base)) base = `N_${base}`;
    let name = adaIdent(base);
    while (used.has(name.toLowerCase())) name += '_X';
    used.add(name.toLowerCase());
    return {
      name,
      has: `Has_${base}`,
      type: adaType(prop.type),
      initialiser: defaultFor(prop.type),
      optional: !prop.required || prop.nullable,
      wire: prop.wire,
      ref: prop.type,
      description: prop.description,
    };
  });
}

function defaultFor(ref: TypeRef): string {
  switch (ref.kind) {
    case 'prim':
      switch (ref.prim) {
        case 'integer':
          return ' := 0';
        case 'number':
          return ' := 0.0';
        case 'boolean':
          return ' := False';
        case 'jsonObject':
          //  The schema says `object`, so an unset required field must render
          //  as `{}`. JSON null would be a different value entirely.
          return ' := UARP.JSON_Support.New_Object';
        case 'json':
          return ' := UARP.JSON_Support.Null_Value';
        default:
          return ' := UARP.Types.Empty_Text';
      }
    case 'union':
    case 'map':
      return ' := UARP.JSON_Support.Null_Value';
    default:
      // Records and vectors default-initialise on their own.
      return '';
  }
}

function emitModelsBody(ordered: NamedType[]): string {
  const w = new Writer('   ');
  w.line(HEADER);
  w.line();
  w.line('package body UARP.Models is');
  w.indent(() => {
    w.line();
    w.line('package JS renames UARP.JSON_Support;');
    w.line();
    for (const type of ordered) {
      if (type.kind === 'enum') emitEnumBody(w, type);
      else if (type.kind === 'object') emitRecordBody(w, type);
    }
  });
  w.line('end UARP.Models;');
  return w.toString();
}

function emitEnumBody(w: Writer, type: EnumType): void {
  const name = typeName(type.name);
  const kind = enumKindType(type.name);
  const literals = enumLiterals(type);

  w.line(`function To_${name} (Value : String) return ${name} is`);
  w.line('begin');
  w.indent(() => {
    let first = true;
    for (const entry of literals.entries) {
      w.line(`${first ? 'if' : 'elsif'} Value = "${escape(entry.wire)}" then`);
      w.indent(() => w.line(`return (Kind => ${entry.literal}, Raw => UARP.Types.\"+\" (Value));`));
      first = false;
    }
    if (first) {
      w.line(`return (Kind => ${literals.unrecognized}, Raw => UARP.Types.\"+\" (Value));`);
    } else {
      w.line('else');
      w.indent(() => w.line(`return (Kind => ${literals.unrecognized}, Raw => UARP.Types.\"+\" (Value));`));
      w.line('end if;');
    }
  });
  w.line(`end To_${name};`);
  w.line();

  w.line(`function To_${name} (Kind : ${kind}) return ${name} is`);
  w.line('begin');
  w.indent(() => {
    w.line('case Kind is');
    w.indent(() => {
      for (const entry of literals.entries) {
        w.line(`when ${entry.literal} =>`);
        w.indent(() => w.line(`return (Kind => Kind, Raw => UARP.Types.\"+\" ("${escape(entry.wire)}"));`));
      }
      w.line(`when ${literals.unrecognized} =>`);
      w.indent(() => w.line(`return (Kind => Kind, Raw => UARP.Types.Empty_Text);`));
    });
    w.line('end case;');
  });
  w.line(`end To_${name};`);
  w.line();

  w.line(`function Image (Model : ${name}) return String is`);
  w.indent(() => {
    w.line(`(if UARP.Types.SU.Length (Model.Raw) > 0`);
    w.line(`   then UARP.Types.SU.To_String (Model.Raw)`);
    w.line(`   else UARP.Types.SU.To_String (To_${name} (Model.Kind).Raw));`);
  });
  w.line();
  w.line(`function To_JSON (Model : ${name}) return UARP.JSON_Support.JSON_Value is`);
  w.indent(() => w.line('(JS.JSON.Create (Image (Model)));'));
  w.line();
  w.line(`function From_JSON (Node : UARP.JSON_Support.JSON_Value) return ${name} is`);
  w.indent(() => w.line(`(To_${name} (UARP.Types.\"+\" (JS.As_Text (Node))));`));
  w.line();
}

function emitRecordBody(w: Writer, type: ObjectType): void {
  const name = typeName(type.name);
  const fields = fieldsOf(type);

  // ---- To_JSON
  w.line(`function To_JSON (Model : ${name}) return UARP.JSON_Support.JSON_Value is`);
  if (fields.length === 0 && !type.additional) {
    w.indent(() => w.line('(JS.New_Object);'));
    w.line();
  } else {
    w.indent(() => w.line('Result : constant UARP.JSON_Support.JSON_Value := JS.New_Object;'));
    w.line('begin');
    w.indent(() => {
      for (const field of fields) {
        if (field.optional) {
          w.line(`if Model.${field.has} then`);
          w.indent(() => emitSetField(w, field));
          w.line('end if;');
        } else {
          emitSetField(w, field);
        }
      }
      w.line('return Result;');
    });
    w.line(`end To_JSON;`);
    w.line();
  }

  // ---- From_JSON
  w.line(`function From_JSON (Node : UARP.JSON_Support.JSON_Value) return ${name} is`);
  if (fields.length === 0 && !type.additional) {
    w.indent(() => w.line(`(${name}'(null record));`));
    w.line();
    return;
  }
  w.indent(() => w.line(`Result : ${name};`));
  w.line('begin');
  w.indent(() => {
    for (const field of fields) {
      w.line(`if JS.Present (Node, "${escape(field.wire)}") then`);
      w.indent(() => {
        if (field.optional) w.line(`Result.${field.has} := True;`);
        emitReadField(w, field);
      });
      w.line('end if;');
    }
    if (type.additional) w.line('Result.Extra := Node;');
    w.line('return Result;');
  });
  w.line('end From_JSON;');
  w.line();
}

function emitSetField(w: Writer, field: Field): void {
  const source = `Model.${field.name}`;
  //  An array of raw JSON has no Ada vector to walk; it is carried verbatim.
  const ref = field.ref;
  if (ref.kind === 'array' && field.type !== 'UARP.JSON_Support.JSON_Value') {
    w.line('declare');
    w.indent(() => w.line(`Items : JS.JSON_Array := JS.JSON.Empty_Array;`));
    w.line('begin');
    w.indent(() => {
      w.line(`for Element of ${source} loop`);
      w.indent(() => w.line(`JS.JSON.Append (Items, ${toJsonExpr(ref.items, 'Element')});`));
      w.line('end loop;');
      w.line(`JS.Set (Result, "${escape(field.wire)}", Items);`);
    });
    w.line('end;');
    return;
  }
  const expr = field.ref.kind === 'array' ? source : toJsonExpr(field.ref, source);
  w.line(`JS.Set (Result, "${escape(field.wire)}", ${expr});`);
}

function emitReadField(w: Writer, field: Field): void {
  const target = `Result.${field.name}`;
  const ref = field.ref;
  if (ref.kind === 'array' && field.type !== 'UARP.JSON_Support.JSON_Value') {
    w.line('declare');
    w.indent(() => {
      w.line(`Items : constant JS.JSON_Array := JS.Get_Array (Node, "${escape(field.wire)}");`);
    });
    w.line('begin');
    w.indent(() => {
      w.line('for Index in 1 .. JS.JSON.Length (Items) loop');
      w.indent(() => {
        w.line(`${target}.Append (${fromJsonExpr(ref.items, 'JS.JSON.Get (Items, Index)')});`);
      });
      w.line('end loop;');
    });
    w.line('end;');
    return;
  }
  const source = `JS.Get_Value (Node, "${escape(field.wire)}")`;
  const expr = field.ref.kind === 'array' ? source : fromJsonExpr(field.ref, source);
  w.line(`${target} := ${expr};`);
}

/** Wrap an Ada value of `ref` into a JSON_Value. */
function toJsonExpr(ref: TypeRef, expr: string): string {
  switch (ref.kind) {
    case 'named':
      return `To_JSON (${expr})`;
    case 'array':
      // Nested arrays are rare; the raw value keeps the data intact.
      return expr;
    case 'map':
    case 'union':
      return expr;
    case 'prim':
      switch (ref.prim) {
        case 'integer':
        case 'number':
        case 'boolean':
          return `JS.JSON.Create (${expr})`;
        case 'json':
        case 'jsonObject':
          return expr;
        default:
          return `JS.JSON.Create (${expr})`;
      }
  }
}

/** Read a JSON_Value into an Ada value of `ref`. */
function fromJsonExpr(ref: TypeRef, expr: string): string {
  switch (ref.kind) {
    case 'named':
      return `From_JSON (${expr})`;
    case 'array':
    case 'map':
    case 'union':
      return expr;
    case 'prim':
      switch (ref.prim) {
        case 'integer':
          return `JS.As_Integer (${expr})`;
        case 'number':
          return `JS.As_Float (${expr})`;
        case 'boolean':
          return `JS.As_Boolean (${expr})`;
        case 'json':
        case 'jsonObject':
          return expr;
        default:
          return `JS.As_Text (${expr})`;
      }
  }
}

/**
 * Every type mark is fully qualified. Inside a record declaration a component
 * name hides any outer name that matches it, and the spec really does have
 * properties called `text` and `value`, so `Text` alone would not always mean
 * `UARP.Types.Text`.
 */
export function adaType(ref: TypeRef): string {
  switch (ref.kind) {
    case 'named':
      return `UARP.Models.${typeName(ref.name)}`;
    case 'array': {
      const items = ref.items;
      if (items.kind === 'named') return `UARP.Models.${vectorName(items.name)}.Vector`;
      if (items.kind === 'prim') {
        switch (items.prim) {
          case 'integer':
            return 'UARP.Types.Integer_Vectors.Vector';
          case 'number':
            return 'UARP.Types.Float_Vectors.Vector';
          case 'boolean':
            return 'UARP.Types.Boolean_Vectors.Vector';
          case 'json':
          case 'jsonObject':
            return 'UARP.JSON_Support.JSON_Value';
          default:
            return 'UARP.Types.Text_Vectors.Vector';
        }
      }
      return 'UARP.JSON_Support.JSON_Value';
    }
    case 'map':
    case 'union':
      return 'UARP.JSON_Support.JSON_Value';
    case 'prim':
      switch (ref.prim) {
        case 'integer':
          return 'UARP.Types.Integer_Value';
        case 'number':
          return 'UARP.Types.Float_Value';
        case 'boolean':
          return 'Standard.Boolean';
        case 'json':
        case 'jsonObject':
          return 'UARP.JSON_Support.JSON_Value';
        default:
          return 'UARP.Types.Text';
      }
  }
}

/** Write `head` followed by an indented, parenthesised argument list. */
function emitArgs(w: Writer, head: string, args: string[], tail = ');'): void {
  w.line(head);
  w.indent(() => {
    args.forEach((arg, index) => {
      const open = index === 0 ? '(' : ' ';
      const close = index === args.length - 1 ? tail : ',';
      w.line(`${open}${arg}${close}`);
    });
  });
}

/** Multi-line declarations are emitted line by line so indentation survives. */
function emitLines(w: Writer, text: string): void {
  for (const line of text.split('\n')) w.line(line);
}

// --------------------------------------------------------------------- api

function emitApiParent(spec: Spec): string {
  const w = new Writer('   ');
  w.line(HEADER);
  w.line('--');
  w.line('--  Parent of the generated operation packages, one per OpenAPI tag:');
  for (const group of spec.groups) {
    w.line(`--    UARP.API.${adaName(group.name)}`);
  }
  w.line();
  w.line('package UARP.API is');
  w.line();
  w.line('end UARP.API;');
  return w.toString();
}

function unitName(group: Group): string {
  return `UARP.API.${adaName(group.name)}`;
}

function emitGroupSpec(group: Group): string {
  const w = new Writer('   ');
  w.line(`package ${unitName(group)} is`);
  w.indent(() => {
    w.line();
    w.line('subtype Client_Type is UARP.Client.Client_Type;');
    w.line('subtype Request_Options is UARP.Client.Request_Options;');
    w.line();

    for (const op of group.operations) {
      const params = paramBag(op);
      if (params.length === 0) continue;
      comment(w, `Query and header parameters for \`${op.id}\`.`);
      w.line(`type ${paramsType(op)} is record`);
      w.indent(() => {
        for (const field of paramFields(op)) {
          comment(w, field.description);
          if (field.optional) w.line(`${field.has} : Boolean := False;`);
          w.line(`${field.name} : ${field.type}${field.initialiser};`);
        }
      });
      w.line('end record;');
      w.line();
      w.line(`No_${paramsType(op)} : constant ${paramsType(op)} := (others => <>);`);
      w.line();
    }

    for (const op of group.operations) {
      comment(w, operationDoc(op));
      emitLines(w, `${signature(op, group)};`);
      w.line();
      if (canCollectPages(op)) {
        comment(
          w,
          `Collect every item \`${op.id}\` returns, following the \`${op.pagination!.cursorProp}\` cursor. Stops early when Max_Items is reached (0 means no limit).`,
        );
        emitLines(w, `${paginatedSignature(op, group)};`);
        w.line();
      }
    }
  });
  w.line(`end ${unitName(group)};`);

  const head = new Writer('   ');
  head.line(HEADER);
  head.line('--');
  if (group.description) head.doc(toAscii(group.description), '--  ');
  head.line();
  for (const unit of neededUnits(w.toString())) head.line(`with ${unit};`);
  head.line();
  return head.toString() + w.toString();
}

/** The units a generated spec already withs, so its body need not repeat them. */
function withClausesOf(specText: string): Set<string> {
  const units = new Set<string>();
  for (const match of specText.matchAll(/^with ([A-Za-z0-9_.]+);$/gm)) units.add(match[1]!);
  return units;
}

/** With-clauses for exactly the units the generated text mentions. */
function neededUnits(text: string): string[] {
  const candidates = ['UARP.Client', 'UARP.JSON_Support', 'UARP.Models', 'UARP.SSE', 'UARP.Types'];
  return candidates.filter((unit) => text.includes(`${unit}.`));
}

function paramsType(op: Operation): string {
  return `${adaName(op.id)}_Params`;
}

function paramFields(op: Operation): Field[] {
  const used = new Set<string>();
  return paramBag(op).map((param) => {
    let base = adaName(param.wire) || 'Value';
    if (/^[0-9]/.test(base)) base = `N_${base}`;
    let name = adaIdent(base);
    while (used.has(name.toLowerCase())) name += '_X';
    used.add(name.toLowerCase());
    return {
      name,
      has: `Has_${base}`,
      type: paramType(param),
      initialiser: defaultFor(param.type),
      optional: !param.required,
      wire: param.wire,
      ref: param.type,
      description: param.description,
    };
  });
}

function paramType(param: Param): string {
  return adaType(param.type);
}

function methodName(op: Operation): string {
  return adaIdent(adaName(op.method));
}

/** Names must be unique within a package; fall back to the full operation id. */
function resolveName(op: Operation, group: Group): string {
  const preferred = methodName(op);
  const clashes = group.operations.filter((other) => methodName(other) === preferred).length;
  return clashes > 1 ? adaIdent(adaName(op.id)) : preferred;
}

function returnType(op: Operation): string | undefined {
  if (op.sse) return undefined;
  if (!op.response.type) return undefined;
  if (op.response.type.kind === 'prim' && op.response.type.prim === 'binary') return 'UARP.Types.Text';
  return adaType(op.response.type);
}

function signature(op: Operation, group: Group): string {
  const name = resolveName(op, group);
  const args = argumentList(op);
  const result = returnType(op);
  const kind = op.sse || result === undefined ? 'procedure' : 'function';
  const rendered = args.map((arg, index) => {
    const open = index === 0 ? '  (' : '   ';
    const close = index === args.length - 1 ? ')' : ';';
    return `${open}${arg}${close}`;
  });
  const lines = [`${kind} ${name}`, ...rendered];
  if (kind === 'function') lines.push(`   return ${result}`);
  return lines.join('\n');
}

function paginatedSignature(op: Operation, group: Group): string {
  const name = `${resolveName(op, group)}_All`;
  const itemType = paginatedItemType(op);
  const args = [...argumentList(op), 'Max_Items : Natural := 0'];
  const rendered = args.map((arg, index) => {
    const open = index === 0 ? '  (' : '   ';
    const close = index === args.length - 1 ? ')' : ';';
    return `${open}${arg}${close}`;
  });
  return [`function ${name}`, ...rendered, `   return ${itemType}`].join('\n');
}

function argumentList(op: Operation): string[] {
  const args: string[] = ['Self : Client_Type'];
  for (const param of op.pathParams) {
    args.push(`${adaIdent(adaName(param.wire))} : String`);
  }
  if (op.body) {
    args.push(`Payload : ${payloadType(op)}`);
    if (!op.body.required) args.push('Include_Payload : Boolean := True');
  }
  if (paramBag(op).length > 0) {
    args.push(`Params : ${paramsType(op)} := No_${paramsType(op)}`);
  }
  if (op.sse) args.push("Sink : in out UARP.SSE.Event_Sink'Class");
  args.push('Options : Request_Options := UARP.Client.Default_Options');
  return args;
}

function emitGroupBody(group: Group, inherited: Set<string>): string {
  const inner = new Writer('   ');
  inner.indent(() => {
    for (const op of group.operations) {
      emitOperationBody(inner, op, group);
      if (canCollectPages(op)) emitPaginatedBody(inner, op, group);
    }
  });
  const text = inner.toString();
  const usesJson = /\bJS\./.test(text);

  const w = new Writer('   ');
  w.line(HEADER);
  w.line();
  //  Only the with-clauses the body actually needs, so builds stay warning-free.
  const units = ['UARP.JSON_Support', 'UARP.Models', 'UARP.Multipart', 'UARP.Types'].filter(
    (unit) =>
      !inherited.has(unit) && (text.includes(`${unit}.`) || (unit === 'UARP.JSON_Support' && usesJson)),
  );
  for (const unit of units) w.line(`with ${unit};`);
  if (units.length > 0) w.line();
  w.line(`package body ${unitName(group)} is`);
  w.line();
  if (usesJson) {
    w.indent(() => {
      w.line('package JS renames UARP.JSON_Support;');
      w.line();
    });
  }
  w.line(text.replace(/\n$/, ''));
  w.line(`end ${unitName(group)};`);
  return w.toString();
}

function emitOperationBody(w: Writer, op: Operation, group: Group): void {
  const result = returnType(op);
  const isFunction = !op.sse && result !== undefined;

  emitLines(w, signature(op, group));
  w.line('is');
  w.indent(() => {
    if (op.queryParams.length > 0) w.line('Query : UARP.Types.Pair_Vectors.Vector;');
    if (op.headerParams.length > 0) w.line('Headers : UARP.Types.Pair_Vectors.Vector;');
  });
  w.line('begin');
  w.indent(() => {
    emitParamAssignments(w, op);
    emitCall(w, op, isFunction);
  });
  w.line(`end ${resolveName(op, group)};`);
  w.line();
}

function emitParamAssignments(w: Writer, op: Operation): void {
  const fields = paramFields(op);
  const bag = paramBag(op);
  for (const [index, param] of bag.entries()) {
    const field = fields[index]!;
    const target = param.location === 'query' ? 'Query' : 'Headers';
    const value = param.type.kind === 'named' ? `UARP.Models.Image (Params.${field.name})` : `Params.${field.name}`;
    const statement = `UARP.Types.Add (${target}, "${escape(param.wire)}", ${value});`;
    if (field.optional) {
      w.line(`if Params.${field.has} then`);
      w.indent(() => w.line(statement));
      w.line('end if;');
    } else {
      w.line(statement);
    }
  }
}

/** Build a `multipart/form-data` body and post it verbatim. */
function emitMultipartCall(w: Writer, op: Operation, args: string[]): void {
  const parts = op.body?.parts ?? [];
  const fields = op.body!.type.kind === 'named' ? parts : [];

  w.line('declare');
  w.indent(() => {
    w.line('Form : UARP.Multipart.Builder;');
  });
  w.line('begin');
  w.indent(() => {
    w.line('UARP.Multipart.Reset (Form);');
    for (const part of fields) {
      const field = adaIdent(adaName(part.wire));
      const accessor = `Payload.${field}`;
      const statement =
        part.role === 'file'
          ? `UARP.Multipart.Add_File (Form, "${escape(part.wire)}", "${escape(part.wire)}", UARP.Types.SU.To_String (${accessor}));`
          : `UARP.Multipart.Add_Field (Form, "${escape(part.wire)}", UARP.Types.SU.To_String (${accessor}));`;
      if (part.required) {
        w.line(statement);
      } else {
        w.line(`if Payload.Has_${adaName(part.wire)} then`);
        w.indent(() => w.line(statement));
        w.line('end if;');
      }
    }
    const rawArgs = args
      .filter((a) => !a.startsWith('Payload =>') && !a.startsWith('Has_Payload =>'))
      .concat([
        'Payload => UARP.Types.SU.To_String (UARP.Multipart.Body_Text (Form))',
        'Has_Payload => True',
        'Content_Type => UARP.Multipart.Content_Type (Form)',
      ]);

    w.line('declare');
    w.indent(() => {
      emitArgs(w, 'Raw_Body : constant UARP.Types.Text := UARP.Client.Call_Raw', rawArgs);
    });
    w.line('begin');
    w.indent(() => {
      const result = returnType(op);
      if (result === undefined) {
        w.line('pragma Unreferenced (Raw_Body);');
        w.line('null;');
      } else if (result === 'UARP.Types.Text') {
        w.line('return Raw_Body;');
      } else if (op.response.type!.kind === 'named') {
        w.line('return UARP.Models.From_JSON (JS.Parse (UARP.Types.SU.To_String (Raw_Body)));');
      } else {
        w.line('return JS.Parse (UARP.Types.SU.To_String (Raw_Body));');
      }
    });
    w.line('end;');
  });
  w.line('end;');
}

function emitCall(w: Writer, op: Operation, isFunction: boolean): void {
  const args: string[] = ['Self', `"${op.httpMethod.toUpperCase()}"`, pathExpr(op)];
  if (op.queryParams.length > 0) args.push('Query => Query');
  if (op.headerParams.length > 0) args.push('Headers => Headers');
  if (op.body) {
    args.push(`Payload => ${payloadExpr(op)}`);
    args.push(op.body.required ? 'Has_Payload => True' : 'Has_Payload => Include_Payload');
  }
  if (op.idempotent) args.push('Idempotent => True');
  args.push('Options => Options');

  if (op.sse) {
    const streamArgs: string[] = ['Self', pathExpr(op), 'Sink'];
    if (op.queryParams.length > 0) streamArgs.push('Query => Query');
    if (op.headerParams.length > 0) streamArgs.push('Headers => Headers');
    streamArgs.push('Options => Options');
    emitArgs(w, 'UARP.Client.Stream', streamArgs);
    return;
  }

  if (op.body?.encoding === 'multipart') {
    emitMultipartCall(w, op, args);
    return;
  }

  //  Text and binary responses come back verbatim rather than as JSON.
  const raw = returnType(op) === 'UARP.Types.Text';
  if (raw) {
    const rawArgs = args.map((a) =>
      a.startsWith('Payload =>') ? `Payload => JS.Serialize (${payloadExpr(op)})` : a,
    );
    emitArgs(w, 'return UARP.Client.Call_Raw', rawArgs);
    return;
  }

  if (!isFunction) {
    emitArgs(w, 'UARP.Client.Call_And_Discard', args);
    return;
  }

  //  A top-level array response is decoded element by element into a vector.
  if (op.response.type!.kind === 'array' && returnType(op) !== 'UARP.JSON_Support.JSON_Value') {
    const items = (op.response.type as { kind: 'array'; items: TypeRef }).items;
    w.line('declare');
    w.indent(() => {
      w.line('Payload_Items : constant JS.JSON_Array := JS.JSON.Get');
      w.indent(() => emitArgs(w, '(UARP.Client.Call', args, '));'));
      w.line(`Collected : ${returnType(op)};`);
    });
    w.line('begin');
    w.indent(() => {
      w.line('for Index in 1 .. JS.JSON.Length (Payload_Items) loop');
      w.indent(() => {
        //  Qualify the element type: `From_JSON` is overloaded on its result.
        const element = items.kind === 'named'
          ? `${adaType(items)}'(UARP.Models.From_JSON (JS.JSON.Get (Payload_Items, Index)))`
          : fromJsonExpr(items, 'JS.JSON.Get (Payload_Items, Index)');
        w.line(`Collected.Append (${element});`);
      });
      w.line('end loop;');
      w.line('return Collected;');
    });
    w.line('end;');
    return;
  }

  const wraps = op.response.type!.kind === 'named';
  if (wraps) {
    w.line('return UARP.Models.From_JSON');
    w.indent(() => emitArgs(w, '(UARP.Client.Call', args, '));'));
  } else {
    emitArgs(w, 'return UARP.Client.Call', args);
  }
}

function emitPaginatedBody(w: Writer, op: Operation, group: Group): void {
  const pagination = op.pagination!;
  const name = `${resolveName(op, group)}_All`;
  const fields = paramFields(op);
  const bag = paramBag(op);
  const cursorIndex = bag.findIndex((p) => p.wire === pagination.cursorParam);
  const cursorField = fields[cursorIndex]!;
  const itemsField = adaName(pagination.itemsProp);
  const cursorProp = adaName(pagination.cursorProp);
  const hasMoreProp = pagination.hasMoreProp ? adaName(pagination.hasMoreProp) : undefined;
  const callArgs = argumentList(op)
    .filter((a) => !a.startsWith('Options :'))
    .map((a) => {
      const argName = a.split(' ')[0]!;
      return argName === 'Params' ? 'Params => Page_Params' : `${argName} => ${argName}`;
    })
    .map((a) => (a === 'Self => Self' ? 'Self' : a));

  emitLines(w, paginatedSignature(op, group));
  w.line('is');
  w.indent(() => {
    w.line(`Collected : ${paginatedItemType(op)};`);
    w.line(`Page_Params : ${paramsType(op)} := Params;`);
    w.line('Seen : UARP.Types.Text_Vectors.Vector;');
  });
  w.line('begin');
  w.indent(() => {
    w.line('loop');
    w.indent(() => {
      w.line('declare');
      w.indent(() => {
        w.line(`Page : constant ${returnType(op)} :=`);
        w.indent(() => emitArgs(w, resolveName(op, group), [...callArgs, 'Options => Options']));
      });
      w.line('begin');
      w.indent(() => {
        w.line(`for Item of Page.${itemsField} loop`);
        w.indent(() => {
          w.line('Collected.Append (Item);');
          w.line('if Max_Items > 0 and then Natural (Collected.Length) >= Max_Items then');
          w.indent(() => w.line('return Collected;'));
          w.line('end if;');
        });
        w.line('end loop;');
        w.line(`exit when Page.${itemsField}.Is_Empty;`);
        if (hasMoreProp) {
          w.line(
            pagination.hasMoreOptional
              ? `exit when Page.Has_${hasMoreProp} and then not Page.${hasMoreProp};`
              : `exit when not Page.${hasMoreProp};`,
          );
        }
        if (pagination.cursorOptional) {
          w.line(`exit when not Page.Has_${cursorProp};`);
        }
        w.line(`exit when UARP.Types.SU.Length (Page.${cursorProp}) = 0;`);
        w.line('--  A server that keeps echoing one cursor must not spin us forever.');
        w.line(`exit when Seen.Contains (Page.${cursorProp});`);
        w.line(`Seen.Append (Page.${cursorProp});`);
        if (cursorField.optional) w.line(`Page_Params.${cursorField.has} := True;`);
        w.line(`Page_Params.${cursorField.name} := Page.${cursorProp};`);
      });
      w.line('end;');
    });
    w.line('end loop;');
    w.line('return Collected;');
  });
  w.line(`end ${name};`);
  w.line();
}

/**
 * Only object-shaped bodies get a generated record; the 62 endpoints whose
 * body is a bare scalar, array or free-form object take raw JSON instead.
 */
function payloadType(op: Operation): string {
  return op.body!.type.kind === 'named' ? adaType(op.body!.type) : 'UARP.JSON_Support.JSON_Value';
}

function payloadExpr(op: Operation): string {
  return op.body!.type.kind === 'named' ? 'UARP.Models.To_JSON (Payload)' : 'Payload';
}

/**
 * The `_All` helper collects into a typed vector, so it is only generated when
 * the page items have a named model type.
 */
function canCollectPages(op: Operation): boolean {
  return op.pagination !== undefined && op.pagination.itemType.kind === 'named';
}

function paginatedItemType(op: Operation): string {
  const item = op.pagination!.itemType;
  return item.kind === 'named'
    ? `UARP.Models.${vectorName(item.name)}.Vector`
    : 'UARP.JSON_Support.JSON_Value';
}

function pathExpr(op: Operation): string {
  if (op.pathParams.length === 0) return `"${escape(op.path)}"`;
  const parts: string[] = [];
  let rest = op.path;
  for (;;) {
    const match = /\{([^}]+)\}/.exec(rest);
    if (!match) {
      if (rest.length > 0) parts.push(`"${escape(rest)}"`);
      break;
    }
    const literal = rest.slice(0, match.index);
    if (literal.length > 0) parts.push(`"${escape(literal)}"`);
    parts.push(`UARP.Types.Encode_Path_Segment (${adaIdent(adaName(match[1]!))})`);
    rest = rest.slice(match.index + match[0].length);
  }
  return parts.join(' & ');
}

function paramBag(op: Operation): Param[] {
  return [...op.queryParams, ...op.headerParams];
}

function operationDoc(op: Operation): string {
  const parts: string[] = [];
  if (op.summary) parts.push(op.summary);
  if (op.description && op.description !== op.summary) parts.push(op.description);
  parts.push(`${op.httpMethod.toUpperCase()} ${op.path}`);
  if (op.scopes.length > 0) parts.push(`Required scopes: ${op.scopes.join(', ')}.`);
  if (op.sse) parts.push('Dispatches every event to Sink until the stream ends or the sink stops it.');
  return parts.join('\n\n');
}

// ------------------------------------------------------------------ helpers

/** Ada needs declarations in dependency order; the spec's graph is acyclic. */
function sortByDependency(types: NamedType[]): NamedType[] {
  const byName = new Map(types.map((t) => [t.name, t]));
  const visited = new Set<string>();
  const visiting = new Set<string>();
  const out: NamedType[] = [];

  const dependencies = (type: NamedType): string[] => {
    const names: string[] = [];
    const walk = (ref: TypeRef): void => {
      if (ref.kind === 'named') names.push(ref.name);
      else if (ref.kind === 'array') walk(ref.items);
      else if (ref.kind === 'map') walk(ref.values);
      else if (ref.kind === 'union') ref.variants.forEach(walk);
    };
    if (type.kind === 'object') type.properties.forEach((p) => walk(p.type));
    if (type.kind === 'alias') walk(type.target);
    return names;
  };

  const visit = (name: string): void => {
    if (visited.has(name) || visiting.has(name)) return;
    const type = byName.get(name);
    if (!type) return;
    visiting.add(name);
    for (const dep of dependencies(type)) visit(dep);
    visiting.delete(name);
    visited.add(name);
    out.push(type);
  };

  for (const type of types) visit(type.name);
  return out;
}

/** Named types that appear as array elements need a Vectors instantiation. */
function collectArrayElements(spec: Spec): Set<string> {
  const names = new Set<string>();
  const walk = (ref: TypeRef): void => {
    if (ref.kind === 'array') {
      if (ref.items.kind === 'named') names.add(ref.items.name);
      walk(ref.items);
    } else if (ref.kind === 'map') walk(ref.values);
    else if (ref.kind === 'union') ref.variants.forEach(walk);
  };
  for (const type of spec.types) {
    if (type.kind === 'object') type.properties.forEach((p) => walk(p.type));
    if (type.kind === 'alias') walk(type.target);
  }
  for (const group of spec.groups) {
    for (const op of group.operations) {
      if (op.pagination?.itemType.kind === 'named') names.add(op.pagination.itemType.name);
      //  A top-level array response or body needs its vector instantiation too.
      if (op.response.type) walk(op.response.type);
      if (op.body) walk(op.body.type);
      for (const param of [...op.pathParams, ...op.queryParams, ...op.headerParams]) walk(param.type);
    }
  }
  return names;
}

function comment(w: Writer, text: string | undefined): void {
  if (!text) return;
  w.doc(toAscii(text), '--  ');
}

/** GNAT reads sources as Latin-1 by default, so comments stay ASCII. */
function toAscii(text: string): string {
  return text
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[–—]/g, '-')
    .replace(/[…]/g, '...')
    .replace(/[^\x20-\x7E\n]/g, '?');
}

function escape(value: string): string {
  return toAscii(value).replace(/"/g, '""').replace(/\n/g, ' ');
}
