/** Kotlin emitter: kotlinx.serialization models plus one `*Api` class per tag. */
import { sdkVersion, type GeneratedFile } from '../index.ts';
import { assertSupportedBody } from '../ir.ts';
import type { EnumType, Group, ObjectType, Operation, Param, Spec, TypeRef } from '../ir.ts';
import { camel, kotlinIdent, pascal, screamingSnake } from '../naming.ts';

/** Body encodings this emitter can render. */
const SUPPORTED_BODIES = ['json', 'multipart', 'binary', 'text'] as const;
import { Writer } from '../writer.ts';

const HEADER = '// Code generated by @uarp/codegen from spec/openapi.json. DO NOT EDIT.';
const ROOT = 'uarp-sdk/src/main/kotlin/ai/snaga/uarp/generated';
const KOTLIN_INDENT = '    ';

const CORE_PACKAGE = 'ai.snaga.uarp';
const MODELS_PACKAGE = 'ai.snaga.uarp.models';
const API_PACKAGE = 'ai.snaga.uarp.api';

/** Names that would shadow a Kotlin built-in or this SDK's own core types. */
const SHADOWED_TYPE_NAMES = new Set([
  'String', 'Int', 'Long', 'Short', 'Byte', 'Double', 'Float', 'Boolean', 'Char', 'Unit', 'Any',
  'Nothing', 'Array', 'List', 'Map', 'Set', 'Pair', 'Triple', 'Result', 'Sequence', 'Iterable',
  'Collection', 'Comparable', 'Number', 'Enum', 'Throwable', 'Exception', 'Error', 'Function',
  'Lazy', 'Regex', 'Json', 'Body', 'Part', 'Problem', 'FieldError', 'ServerEvent', 'StreamOptions',
  'RequestOptions', 'RequestSpec', 'UarpClient', 'FilePart', 'ApiException', 'UarpException',
]);

function typeName(name: string): string {
  return SHADOWED_TYPE_NAMES.has(name) ? `${name}Model` : name;
}

export function emitKotlin(spec: Spec): GeneratedFile[] {
  for (const group of spec.groups) {
    for (const op of group.operations) assertSupportedBody(op, [...SUPPORTED_BODIES]);
  }
  const files: GeneratedFile[] = [];
  files.push({ path: `${ROOT}/Meta.kt`, content: emitMeta(spec) });
  files.push({ path: `${ROOT}/Models.kt`, content: emitModels(spec) });
  for (const group of spec.groups) {
    files.push({ path: `${ROOT}/api/${group.name}Api.kt`, content: emitGroup(group) });
  }
  return files;
}

function emitMeta(spec: Spec): string {
  const w = new Writer(KOTLIN_INDENT);
  w.line(HEADER);
  w.line();
  w.line(`package ${CORE_PACKAGE}`);
  w.line();
  w.line('/** Version of the OpenAPI document this SDK was generated from. */');
  w.line(`public const val SPEC_VERSION: String = "${escape(spec.version)}"`);
  w.line();
  w.line('/** Version of this SDK. */');
  w.line(`public const val SDK_VERSION: String = "${escape(sdkVersion())}"`);
  w.line();
  w.line('/** Production base URL. */');
  w.line(`public const val DEFAULT_BASE_URL: String = "${escape(spec.servers[0]?.url ?? 'https://api.snaga.ai')}"`);
  w.line();
  w.line('/** Every scope named by the UARP security scheme. */');
  w.line('public val SCOPES: List<String> = listOf(');
  w.indent(() => {
    for (const scope of spec.scopes) w.line(`"${escape(scope)}",`);
  });
  w.line(')');
  return w.toString();
}

// ------------------------------------------------------------------- models

function emitModels(spec: Spec): string {
  const w = new Writer(KOTLIN_INDENT);
  w.line(HEADER);
  w.line();
  w.line(`package ${MODELS_PACKAGE}`);
  w.line();
  w.line('import ai.snaga.uarp.FilePart');
  w.line('import kotlinx.serialization.KSerializer');
  w.line('import kotlinx.serialization.SerialName');
  w.line('import kotlinx.serialization.Serializable');
  w.line('import kotlinx.serialization.SerializationException');
  w.line('import kotlinx.serialization.descriptors.PrimitiveKind');
  w.line('import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor');
  w.line('import kotlinx.serialization.descriptors.SerialDescriptor');
  w.line('import kotlinx.serialization.encoding.Decoder');
  w.line('import kotlinx.serialization.encoding.Encoder');
  w.line('import kotlinx.serialization.json.JsonDecoder');
  w.line('import kotlinx.serialization.json.JsonElement');
  w.line('import kotlinx.serialization.json.JsonEncoder');
  w.line('import kotlinx.serialization.json.JsonObject');
  w.line('import kotlinx.serialization.json.jsonObject');
  w.line();

  for (const type of spec.types) {
    if (type.kind === 'enum') emitEnum(w, type);
    else if (type.kind === 'object') emitDataClass(w, type);
    else {
      doc(w, type.description);
      w.line(`public typealias ${typeName(type.name)} = ${kotlinType(type.target)}`);
    }
    w.line();
  }
  return w.toString();
}

interface Field {
  kotlin: string;
  wire: string;
  type: string;
  optional: boolean;
  description?: string;
  deprecated?: boolean;
}

function fieldsOf(type: ObjectType): Field[] {
  const used = new Set<string>();
  return type.properties.map((prop) => {
    let name = camel(prop.wire);
    if (name === '' || /^[0-9]/.test(name)) name = `field${pascal(prop.wire)}`;
    while (used.has(name)) name += '_';
    used.add(name);
    return {
      kotlin: kotlinIdent(name),
      wire: prop.wire,
      type: kotlinType(prop.type),
      optional: !prop.required || prop.nullable,
      description: prop.description,
      deprecated: prop.deprecated,
    };
  });
}

function emitDataClass(w: Writer, type: ObjectType): void {
  const fields = fieldsOf(type);
  const name = typeName(type.name);
  const keepsExtra = type.additional !== null;

  doc(w, type.description ?? `\`${type.name}\` model.`);
  if (fields.length === 0 && !keepsExtra) {
    w.line('@Serializable');
    w.line(`public class ${name}`);
    return;
  }

  w.line(keepsExtra ? `@Serializable(with = ${name}Serializer::class)` : '@Serializable');
  w.block(`public data class ${name}(`, () => {
    emitFields(w, fields, 'public ');
    if (keepsExtra) {
      doc(w, 'Properties the server returned that this SDK does not model.');
      w.line('public val additionalProperties: JsonObject = JsonObject(emptyMap()),');
    }
  }, ')');

  if (keepsExtra) {
    w.line();
    emitExtraSerializer(w, name, fields);
  }
}

function emitFields(w: Writer, fields: Field[], visibility: string): void {
  for (const field of fields) {
    const notes = [field.description, field.deprecated ? 'Deprecated by the API.' : undefined]
      .filter(Boolean)
      .join(' ');
    doc(w, notes || undefined);
    if (stripBackticks(field.kotlin) !== field.wire) w.line(`@SerialName("${escape(field.wire)}")`);
    w.line(`${visibility}val ${field.kotlin}: ${field.type}${field.optional ? '? = null' : ''},`);
  }
}

/**
 * kotlinx.serialization drops keys it does not know about. For schemas that
 * declare `additionalProperties` the other SDKs keep them, so these types round
 * trip through a private surrogate: the declared fields go through the
 * generated serializer, everything else lands in `additionalProperties`.
 */
function emitExtraSerializer(w: Writer, name: string, fields: Field[]): void {
  doc(w, `Serializer for [${name}] that preserves unmodelled properties.`);
  w.block(`public object ${name}Serializer : KSerializer<${name}> {`, () => {
    w.line('@Serializable');
    w.line(`@SerialName("${escape(name)}")`);
    w.block('private data class Surrogate(', () => {
      emitFields(w, fields, '');
    }, ')');
    w.line();
    w.line(`private val declaredNames: Set<String> = setOf(${fields.map((f) => `"${escape(f.wire)}"`).join(', ')})`);
    w.line();
    w.line('override val descriptor: SerialDescriptor = Surrogate.serializer().descriptor');
    w.line();
    w.block(`override fun deserialize(decoder: Decoder): ${name} {`, () => {
      w.line('val input = decoder as? JsonDecoder');
      w.line(`    ?: throw SerializationException("${escape(name)} can only be read from JSON")`);
      w.line('val node = input.decodeJsonElement().jsonObject');
      w.line('val declared = input.json.decodeFromJsonElement(Surrogate.serializer(), node)');
      w.block(`return ${name}(`, () => {
        for (const field of fields) w.line(`${field.kotlin} = declared.${field.kotlin},`);
        w.line('additionalProperties = JsonObject(node.filterKeys { it !in declaredNames }),');
      }, ')');
    }, '}');
    w.line();
    w.block(`override fun serialize(encoder: Encoder, value: ${name}) {`, () => {
      w.line('val output = encoder as? JsonEncoder');
      w.line(`    ?: throw SerializationException("${escape(name)} can only be written as JSON")`);
      w.block('val declared = Surrogate(', () => {
        for (const field of fields) w.line(`${field.kotlin} = value.${field.kotlin},`);
      }, ')');
      w.line('val rendered = output.json.encodeToJsonElement(Surrogate.serializer(), declared).jsonObject');
      w.line('output.encodeJsonElement(JsonObject(rendered + value.additionalProperties))');
    }, '}');
  }, '}');
}

/**
 * Enums become string-backed value classes rather than Kotlin `enum class`es:
 * the API can add a value at any time and an unknown one must not fail decoding.
 */
function emitEnum(w: Writer, type: EnumType): void {
  const name = typeName(type.name);
  const cases = enumCases(type);

  doc(w, type.description ?? `\`${type.name}\` values.`);
  w.line('///');
  doc(w, 'Values the API adds later decode unchanged, so a new server-side case never breaks an existing client.');
  w.line(`@Serializable(with = ${name}Serializer::class)`);
  w.line('@JvmInline');
  w.block(`public value class ${name}(public val value: String) {`, () => {
    w.line('override fun toString(): String = value');
    w.line();
    w.block('public companion object {', () => {
      for (const entry of cases) {
        w.line(`public val ${entry.name}: ${name} = ${name}("${escape(entry.wire)}")`);
      }
      w.line();
      w.line('/** Every value the spec declared at generation time. */');
      w.line(`public val knownValues: List<${name}> = listOf(${cases.map((c) => c.name).join(', ')})`);
    }, '}');
  }, '}');
  w.line();
  w.block(`public object ${name}Serializer : KSerializer<${name}> {`, () => {
    w.line(
      `override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("${MODELS_PACKAGE}.${name}", PrimitiveKind.STRING)`,
    );
    w.line(`override fun serialize(encoder: Encoder, value: ${name}): Unit = encoder.encodeString(value.value)`);
    w.line(`override fun deserialize(decoder: Decoder): ${name} = ${name}(decoder.decodeString())`);
  }, '}');
}

interface EnumCase {
  name: string;
  wire: string;
}

function enumCases(type: EnumType): EnumCase[] {
  const used = new Set<string>();
  const out: EnumCase[] = [];
  for (const value of type.values) {
    let name = screamingSnake(value) || 'EMPTY';
    if (/^[0-9]/.test(name)) name = `V${name}`;
    while (used.has(name)) name += '_';
    used.add(name);
    out.push({ name, wire: value });
  }
  return out;
}

// ---------------------------------------------------------------------- api

function emitGroup(group: Group): string {
  const w = new Writer(KOTLIN_INDENT);
  const paginated = group.operations.filter((op) => op.pagination);

  w.line(HEADER);
  w.line();
  w.line('@file:Suppress("unused", "UNUSED_IMPORT", "RedundantVisibilityModifier")');
  w.line();
  w.line(`package ${API_PACKAGE}`);
  w.line();
  w.line(`import ${CORE_PACKAGE}.Body`);
  w.line(`import ${CORE_PACKAGE}.FilePart`);
  w.line(`import ${CORE_PACKAGE}.Part`);
  w.line(`import ${CORE_PACKAGE}.RequestOptions`);
  w.line(`import ${CORE_PACKAGE}.RequestSpec`);
  w.line(`import ${CORE_PACKAGE}.ServerEvent`);
  w.line(`import ${CORE_PACKAGE}.UarpClient`);
  w.line(`import ${CORE_PACKAGE}.autoPaginate`);
  w.line(`import ${CORE_PACKAGE}.encodePathSegment`);
  w.line(`import ${CORE_PACKAGE}.uarpJson`);
  w.line(`import ${MODELS_PACKAGE}.*`);
  w.line('import kotlinx.serialization.encodeToString');
  w.line('import kotlinx.serialization.json.JsonElement');
  w.line('import kotlinx.serialization.json.JsonObject');
  if (paginated.length > 0 || group.operations.some((op) => op.sse)) {
    w.line('import kotlinx.coroutines.flow.Flow');
  }
  w.line();

  doc(w, group.description ?? `Operations tagged \`${group.tag}\`.`);
  w.block(`public class ${group.name}Api internal constructor(private val client: UarpClient) {`, () => {
    let first = true;
    for (const op of group.operations) {
      if (!first) w.line();
      first = false;
      emitOperation(w, op);
      if (op.pagination) {
        w.line();
        emitPaginated(w, op, group);
      }
    }
  }, '}');
  w.line();
  doc(w, group.description ?? `Operations tagged \`${group.tag}\`.`);
  w.line(
    `public val UarpClient.${kotlinIdent(camel(group.accessor))}: ${group.name}Api get() = ${group.name}Api(this)`,
  );
  return w.toString();
}

interface Arg {
  name: string;
  type: string;
  optional: boolean;
  /** The parameter this argument came from, when it is a query/header value. */
  param?: Param;
}

function operationArgs(op: Operation): Arg[] {
  const args: Arg[] = [];
  const used = new Set<string>();
  const unique = (name: string): string => {
    let candidate = name;
    while (used.has(candidate)) candidate += '_';
    used.add(candidate);
    return candidate;
  };

  for (const param of op.pathParams) {
    args.push({ name: kotlinIdent(unique(camel(param.wire))), type: kotlinType(param.type), optional: false });
  }
  if (op.body) {
    args.push({ name: kotlinIdent(unique('body')), type: bodyType(op), optional: !op.body.required });
  }
  for (const param of [...op.queryParams, ...op.headerParams]) {
    args.push({
      name: kotlinIdent(unique(camel(param.wire))),
      type: kotlinType(param.type),
      optional: !param.required,
      param,
    });
  }
  return args;
}

function renderSignature(args: Arg[]): string {
  return [
    ...args.map((a) => `${a.name}: ${a.type}${a.optional ? '? = null' : ''}`),
    'options: RequestOptions = RequestOptions()',
  ].join(', ');
}

function emitOperation(w: Writer, op: Operation): void {
  const args = operationArgs(op);
  doc(w, operationDoc(op));
  if (op.deprecated) w.line('@Deprecated("Deprecated by the API")');

  if (op.sse) {
    w.block(`public fun ${methodName(op)}(${renderSignature(args)}): Flow<ServerEvent> {`, () => {
      emitBody(w, op, args, 'stream');
    }, '}');
    return;
  }

  const kind = callKind(op);
  const returns = kind === 'unit' ? '' : `: ${returnType(op)}`;
  w.block(`public suspend fun ${methodName(op)}(${renderSignature(args)})${returns} {`, () => {
    emitBody(w, op, args, kind);
  }, '}');
}

type CallKind = 'json' | 'unit' | 'bytes' | 'stream';

function callKind(op: Operation): CallKind {
  if (!op.response.type) return 'unit';
  if (op.response.type.kind === 'prim' && op.response.type.prim === 'binary') return 'bytes';
  return 'json';
}

function emitBody(w: Writer, op: Operation, args: Arg[], kind: CallKind): void {
  if (op.queryParams.length > 0) {
    w.block('val query = buildList {', () => {
      for (const param of op.queryParams) {
        const arg = argFor(args, param);
        if (param.required) {
          w.line(`add("${escape(param.wire)}" to ${wireValue(param.type, arg.name)})`);
        } else {
          w.line(`if (${arg.name} != null) add("${escape(param.wire)}" to ${wireValue(param.type, arg.name)})`);
        }
      }
    }, '}');
  }
  if (op.headerParams.length > 0) {
    w.block('val headers = buildList {', () => {
      for (const param of op.headerParams) {
        const arg = argFor(args, param);
        if (param.required) {
          w.line(`add("${escape(param.wire)}" to ${wireValue(param.type, arg.name)})`);
        } else {
          w.line(`if (${arg.name} != null) add("${escape(param.wire)}" to ${wireValue(param.type, arg.name)})`);
        }
      }
    }, '}');
  }
  if (op.body?.encoding === 'multipart') emitMultipart(w, op, args);

  const call =
    kind === 'stream'
      ? 'return client.stream'
      : kind === 'unit'
        ? 'client.requestUnit'
        : kind === 'bytes'
          ? 'return client.requestBytes'
          : `return client.request<${returnType(op)}>`;

  w.line(`${call}(`);
  w.indent(() => {
    w.line('RequestSpec(');
    w.indent(() => {
      w.line(`method = "${op.httpMethod.toUpperCase()}",`);
      w.line(`path = ${pathExpr(op, args)},`);
      if (op.queryParams.length > 0) w.line('query = query,');
      if (op.headerParams.length > 0) w.line('headers = headers,');
      if (op.body) w.line(`body = ${bodyExpr(op, args)},`);
      if (op.idempotent) w.line('idempotent = true,');
      w.line('options = options,');
    });
    w.line(')');
  });
  w.line(')');
}

function argFor(args: Arg[], param: Param): Arg {
  const found = args.find((a) => a.param === param);
  if (!found) throw new Error(`no argument generated for parameter ${param.wire}`);
  return found;
}

/** Render a parameter as a query/header string. */
function wireValue(ref: TypeRef, name: string): string {
  if (ref.kind === 'named') return `${name}.value`;
  if (ref.kind === 'prim' && ['string', 'uuid', 'uri', 'email', 'date', 'datetime'].includes(ref.prim)) return name;
  return `${name}.toString()`;
}

function emitMultipart(w: Writer, op: Operation, args: Arg[]): void {
  const bodyArg = args[op.pathParams.length]!;
  w.block('val parts = buildList {', () => {
    for (const part of op.body?.parts ?? []) {
      const accessor = `${bodyArg.name}.${kotlinIdent(camel(part.wire))}`;
      if (part.role === 'file') {
        if (part.required) {
          w.line(`add(Part.File("${escape(part.wire)}", ${accessor}))`);
        } else {
          w.line(`${accessor}?.let { add(Part.File("${escape(part.wire)}", it)) }`);
        }
      } else if (part.required) {
        w.line(`add(Part.Text("${escape(part.wire)}", ${accessor}))`);
      } else {
        w.line(`${accessor}?.let { add(Part.Text("${escape(part.wire)}", it)) }`);
      }
    }
  }, '}');
}

function bodyExpr(op: Operation, args: Arg[]): string {
  const body = op.body!;
  const label = args[op.pathParams.length]!.name;
  if (body.encoding === 'multipart') return 'Body.Multipart(parts)';
  if (body.encoding === 'binary') return `Body.Raw(${label}, "application/octet-stream")`;
  if (body.encoding === 'text') return `Body.Raw(${label}.toByteArray(), "text/plain")`;
  const encoded = `Body.Json(uarpJson.encodeToString(${label}))`;
  return body.required ? encoded : `${label}?.let { Body.Json(uarpJson.encodeToString(it)) }`;
}

function emitPaginated(w: Writer, op: Operation, group: Group): void {
  const pagination = op.pagination!;
  const args = operationArgs(op);
  const itemType = kotlinType(pagination.itemType);
  const name = paginatedName(op, group);
  const cursorArg = args.find((a) => a.param?.wire === pagination.cursorParam)!;
  const callArgs = args.map((a) => `${a.name} = ${a.name === cursorArg.name ? 'pageCursor' : a.name}`);

  doc(
    w,
    `Stream every item returned by \`${op.id}\`, following the \`${pagination.cursorProp}\` cursor until the server reports no further pages.`,
  );
  w.block(`public fun ${name}(${renderSignature(args)}): Flow<${itemType}> = autoPaginate(`, () => {
    w.line(`fetch = { pageCursor -> ${methodName(op)}(${[...callArgs, 'options = options'].join(', ')}) },`);
    w.line(
      pagination.itemsOptional
        ? `items = { it.${kotlinIdent(camel(pagination.itemsProp))} ?: emptyList() },`
        : `items = { it.${kotlinIdent(camel(pagination.itemsProp))} },`,
    );
    w.line(`cursor = { it.${kotlinIdent(camel(pagination.cursorProp))} },`);
    w.line(
      pagination.hasMoreProp
        ? `hasMore = { it.${kotlinIdent(camel(pagination.hasMoreProp))} },`
        : 'hasMore = { null },',
    );
  }, ')');
}

function paginatedName(op: Operation, group: Group): string {
  const base = `${methodName(op)}All`;
  return group.operations.some((other) => methodName(other) === base) ? `${methodName(op)}AutoPaging` : base;
}

function pathExpr(op: Operation, args: Arg[]): string {
  if (op.pathParams.length === 0) return `"${escape(op.path)}"`;
  let out = '"';
  let rest = op.path;
  for (;;) {
    const match = /\{([^}]+)\}/.exec(rest);
    if (!match) {
      out += escape(rest);
      break;
    }
    out += escape(rest.slice(0, match.index));
    const index = op.pathParams.findIndex((p) => p.wire === match[1]);
    const arg = args[index]!;
    const value = arg.type === 'String' ? arg.name : `${arg.name}.toString()`;
    out += '${encodePathSegment(' + value + ')}';
    rest = rest.slice(match.index + match[0].length);
  }
  return out + '"';
}

function methodName(op: Operation): string {
  return kotlinIdent(camel(op.method));
}

function bodyType(op: Operation): string {
  const body = op.body!;
  if (body.encoding === 'binary') return 'ByteArray';
  if (body.encoding === 'text') return 'String';
  return kotlinType(body.type);
}

function returnType(op: Operation): string {
  if (!op.response.type) return 'Unit';
  if (op.response.type.kind === 'prim' && op.response.type.prim === 'binary') return 'ByteArray';
  return kotlinType(op.response.type);
}

export function kotlinType(ref: TypeRef): string {
  switch (ref.kind) {
    case 'named':
      return typeName(ref.name);
    case 'array':
      return `List<${kotlinType(ref.items)}>`;
    case 'map':
      return `Map<String, ${kotlinType(ref.values)}>`;
    case 'union':
      // Kotlin has no structural unions; raw JSON keeps every variant reachable.
      return 'JsonElement';
    case 'prim':
      switch (ref.prim) {
        case 'string':
        case 'datetime':
        case 'date':
        case 'uuid':
        case 'uri':
        case 'email':
          return 'String';
        case 'integer':
          return 'Long';
        case 'number':
          return 'Double';
        case 'boolean':
          return 'Boolean';
        case 'binary':
          return 'FilePart';
        case 'jsonObject':
          return 'JsonObject';
        default:
          return 'JsonElement';
      }
  }
}

function operationDoc(op: Operation): string {
  const parts: string[] = [];
  if (op.summary) parts.push(op.summary);
  if (op.description && op.description !== op.summary) parts.push(op.description);
  parts.push(`\`${op.httpMethod.toUpperCase()} ${op.path}\``);
  if (op.scopes.length > 0) parts.push(`Required scopes: ${op.scopes.map((s) => `\`${s}\``).join(', ')}.`);
  if (op.sse) parts.push('Returns a cold flow of server-sent events.');
  return parts.join('\n\n');
}

function doc(w: Writer, text: string | undefined): void {
  if (!text) return;
  // KDoc treats `[...]` as a link. Kotlin block comments nest, so both `/*`
  // and `*/` inside a description would derail the parser.
  const safe = text
    .replace(/\*\//g, '*&#47;')
    .replace(/\/\*/g, '&#47;*')
    .replace(/[[\]]/g, (match) => `\\${match}`);
  w.doc(safe, ' * ', '/**', ' */');
}

function escape(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$')
    .replace(/\n/g, '\\n');
}

function stripBackticks(name: string): string {
  return name.replace(/`/g, '');
}
