/** Rust emitter: serde models plus one `*Api` accessor per tag. */
import type { GeneratedFile } from '../index.ts';
import { assertSupportedBody } from '../ir.ts';
import type { EnumType, Group, ObjectType, Operation, Param, Spec, TypeRef } from '../ir.ts';
import { pascal, rustIdent, snake } from '../naming.ts';

/** Body encodings this emitter can render. */
const SUPPORTED_BODIES = ['json', 'multipart', 'binary', 'text'] as const;
import { Writer } from '../writer.ts';

const HEADER = '// Code generated by @uarp/codegen from spec/openapi.json. DO NOT EDIT.';

/** rustfmt's default indentation, so generated files match hand-written ones. */
const RUST_INDENT = '    ';

export function emitRust(spec: Spec): GeneratedFile[] {
  for (const group of spec.groups) {
    for (const op of group.operations) assertSupportedBody(op, [...SUPPORTED_BODIES]);
  }
  const files: GeneratedFile[] = [];
  files.push({ path: 'src/generated/mod.rs', content: emitRootModule() });
  files.push({ path: 'src/generated/meta.rs', content: emitMeta(spec) });
  files.push({ path: 'src/generated/models.rs', content: emitModels(spec) });
  files.push({ path: 'src/generated/api/mod.rs', content: emitApiModule(spec) });
  for (const group of spec.groups) {
    files.push({ path: `src/generated/api/${snake(group.name)}.rs`, content: emitGroup(group) });
  }
  return files;
}

function emitRootModule(): string {
  const w = new Writer(RUST_INDENT);
  w.line(HEADER);
  w.line();
  w.line('pub mod api;');
  w.line('pub mod meta;');
  w.line('pub mod models;');
  return w.toString();
}

function emitMeta(spec: Spec): string {
  const w = new Writer(RUST_INDENT);
  w.line(HEADER);
  w.line();
  w.line('/// Version of the OpenAPI document this SDK was generated from.');
  w.line(`pub const SPEC_VERSION: &str = "${escape(spec.version)}";`);
  w.line();
  w.line('/// Production base URL.');
  w.line(`pub const DEFAULT_BASE_URL: &str = "${escape(spec.servers[0]?.url ?? 'https://api.snaga.ai')}";`);
  w.line();
  w.line('/// Every scope named by the UARP security scheme.');
  w.line(`pub const SCOPES: [&str; ${spec.scopes.length}] = [`);
  w.indent(() => {
    for (const scope of spec.scopes) w.line(`"${escape(scope)}",`);
  });
  w.line('];');
  return w.toString();
}

// ------------------------------------------------------------------- models

function emitModels(spec: Spec): string {
  const w = new Writer(RUST_INDENT);
  w.line(HEADER);
  w.line('//!');
  w.line(`//! Data models for ${escapeDoc(spec.title)} (spec version ${spec.version}).`);
  w.line();
  w.line('#![allow(unused_imports, clippy::large_enum_variant)]');
  w.line();
  w.line('use std::collections::HashMap;');
  w.line();
  w.line('use serde::{Deserialize, Serialize};');
  w.line();
  w.line('use crate::multipart::FilePart;');
  w.line();

  for (const type of spec.types) {
    if (type.kind === 'enum') emitEnum(w, type);
    else if (type.kind === 'object') emitStruct(w, type);
    else {
      docComment(w, type.description);
      w.line(`pub type ${type.name} = ${rustType(type.target, false)};`);
    }
    w.line();
  }
  return w.toString();
}

function emitStruct(w: Writer, type: ObjectType): void {
  docComment(w, type.description ?? `\`${type.name}\` model.`);
  w.line('#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]');
  w.block(`pub struct ${type.name} {`, () => {
    for (const prop of type.properties) {
      const field = rustIdent(snake(prop.wire));
      const optional = !prop.required || prop.nullable;
      const inner = rustType(prop.type, false);
      const ty = optional ? `Option<${inner}>` : inner;

      const docs: string[] = [];
      if (prop.description) docs.push(prop.description);
      if (prop.constValue !== undefined) docs.push(`Always \`${prop.constValue}\`.`);
      if (prop.defaultValue !== undefined) docs.push(`Server default: \`${JSON.stringify(prop.defaultValue)}\`.`);
      docComment(w, docs.join('\n\n'));

      const attrs: string[] = [];
      if (stripRaw(field) !== prop.wire) attrs.push(`rename = "${escape(prop.wire)}"`);
      if (optional) {
        attrs.push('default');
        // A required-but-nullable property must still serialize as `null`.
        if (!prop.required) attrs.push('skip_serializing_if = "Option::is_none"');
      }
      if (attrs.length > 0) w.line(`#[serde(${attrs.join(', ')})]`);
      w.line(`pub ${field}: ${ty},`);
    }
    if (type.additional) {
      docComment(w, 'Any additional properties the server returned.');
      w.line('#[serde(flatten)]');
      w.line('pub extra: HashMap<String, serde_json::Value>,');
    }
  }, '}');
}

function emitEnum(w: Writer, type: EnumType): void {
  docComment(w, type.description ?? `\`${type.name}\` enumeration.`);
  w.line('#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]');
  const variants = enumVariants(type);
  const catchAll = catchAllName(variants);
  w.block(`pub enum ${type.name} {`, () => {
    for (const [index, variant] of variants.entries()) {
      if (index === 0) w.line('#[default]');
      w.line(`#[serde(rename = "${escape(variant.wire)}")]`);
      w.line(`${variant.name},`);
    }
    docComment(w, 'A value the API introduced after this SDK was generated.');
    w.line('#[serde(untagged)]');
    w.line(`${catchAll}(String),`);
  }, '}');
  w.line();
  w.block(`impl ${type.name} {`, () => {
    w.line('/// The value as it appears on the wire.');
    w.block('pub fn as_str(&self) -> &str {', () => {
      w.block('match self {', () => {
        for (const variant of variants) w.line(`Self::${variant.name} => "${escape(variant.wire)}",`);
        w.line(`Self::${catchAll}(value) => value.as_str(),`);
      }, '}');
    }, '}');
  }, '}');
  w.line();
  w.block(`impl std::fmt::Display for ${type.name} {`, () => {
    w.block("fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {", () => {
      w.line('f.write_str(self.as_str())');
    }, '}');
  }, '}');
  w.line();
  w.block(`impl From<&str> for ${type.name} {`, () => {
    w.block('fn from(value: &str) -> Self {', () => {
      w.block('match value {', () => {
        for (const variant of variants) w.line(`"${escape(variant.wire)}" => Self::${variant.name},`);
        w.line(`other => Self::${catchAll}(other.to_string()),`);
      }, '}');
    }, '}');
  }, '}');
}

interface Variant {
  name: string;
  wire: string;
}

/**
 * Pick a name for the forward-compatible catch-all variant that no declared
 * value already claims (`"other"` is a real value in several of these enums).
 */
function catchAllName(variants: Variant[]): string {
  const taken = new Set(variants.map((v) => v.name));
  for (const candidate of ['Other', 'Unknown', 'Unrecognized']) {
    if (!taken.has(candidate)) return candidate;
  }
  let n = 2;
  while (taken.has(`Other${n}`)) n++;
  return `Other${n}`;
}

function enumVariants(type: EnumType): Variant[] {
  const used = new Set<string>();
  const out: Variant[] = [];
  for (const value of type.values) {
    let name = pascal(value) || 'Empty';
    if (/^[0-9]/.test(name)) name = `V${name}`;
    if (used.has(name)) {
      let n = 2;
      while (used.has(`${name}${n}`)) n++;
      name = `${name}${n}`;
    }
    used.add(name);
    out.push({ name, wire: value });
  }
  return out;
}

// ---------------------------------------------------------------------- api

function emitApiModule(spec: Spec): string {
  const w = new Writer(RUST_INDENT);
  w.line(HEADER);
  w.line('//!');
  w.line('//! One module per OpenAPI tag.');
  w.line();
  for (const group of spec.groups) w.line(`pub mod ${snake(group.name)};`);
  w.line();
  for (const group of spec.groups) w.line(`pub use ${snake(group.name)}::*;`);
  return w.toString();
}

function emitGroup(group: Group): string {
  const w = new Writer(RUST_INDENT);
  const paginated = group.operations.filter(canPaginate);

  w.line(HEADER);
  w.line('//!');
  w.doc(escapeDoc(group.description ?? `Operations tagged \`${group.tag}\`.`), '//! ');
  w.line();
  w.line('#![allow(unused_imports, clippy::too_many_arguments)]');
  w.line();
  w.line('use reqwest::Method;');
  w.line('use serde::{Deserialize, Serialize};');
  if (paginated.length > 0) w.line('use futures_core::Stream;');
  w.line();
  w.line('use crate::client::{Client, Request, NO_BODY, NO_QUERY};');
  w.line('use crate::error::Result;');
  w.line('use crate::generated::models;');
  w.line('use crate::multipart::{field_text, FilePart};');
  if (paginated.length > 0) w.line('use crate::pagination::CursorGuard;');
  if (group.operations.some((op) => op.sse)) w.line('use crate::sse::EventStream;');
  w.line('use crate::util::encode_path;');
  w.line();

  for (const op of group.operations) {
    const params = paramBag(op);
    if (params.length === 0) continue;
    emitParams(w, op, params);
    w.line();
  }

  docComment(w, group.description ?? `Operations tagged \`${group.tag}\`.`);
  w.line('#[derive(Debug, Clone)]');
  w.block(`pub struct ${group.name}Api {`, () => {
    w.line('pub(crate) client: Client,');
  }, '}');
  w.line();
  w.block('impl Client {', () => {
    docComment(w, group.description ?? `Operations tagged \`${group.tag}\`.`);
    w.block(`pub fn ${snake(group.accessor)}(&self) -> ${group.name}Api {`, () => {
      w.line(`${group.name}Api { client: self.clone() }`);
    }, '}');
  }, '}');
  w.line();
  w.block(`impl ${group.name}Api {`, () => {
    let first = true;
    for (const op of group.operations) {
      if (!first) w.line();
      first = false;
      emitOperation(w, op);
      if (canPaginate(op)) {
        w.line();
        emitPaginated(w, op, group);
      }
    }
  }, '}');
  return w.toString();
}

function emitParams(w: Writer, op: Operation, params: Param[]): void {
  docComment(w, `Query and header parameters for \`${op.id}\`.`);
  w.line('#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]');
  w.block(`pub struct ${pascal(op.id)}Params {`, () => {
    for (const param of params) {
      docComment(w, param.description);
      const field = rustIdent(snake(param.wire));
      const inner = rustType(param.type, true);
      const ty = param.required ? inner : `Option<${inner}>`;
      const attrs: string[] = [];
      if (param.location === 'header') {
        // Header values are applied separately, never as query parameters.
        attrs.push('skip');
      } else {
        if (stripRaw(field) !== param.wire) attrs.push(`rename = "${escape(param.wire)}"`);
        if (!param.required) attrs.push('default', 'skip_serializing_if = "Option::is_none"');
      }
      if (attrs.length > 0) w.line(`#[serde(${attrs.join(', ')})]`);
      w.line(`pub ${field}: ${ty},`);
    }
  }, '}');
}

function emitOperation(w: Writer, op: Operation): void {
  const args = operationArgs(op);
  const signature = ['&self', ...args.map((a) => `${a.name}: ${a.type}`)].join(', ');

  docComment(w, operationDoc(op));
  if (op.deprecated) w.line('#[deprecated]');

  if (op.sse) {
    w.block(`pub fn ${methodName(op)}(${signature}) -> EventStream {`, () => {
      emitHeaderLocals(w, op);
      emitCall(w, op, 'stream');
    }, '}');
    return;
  }

  w.block(`pub async fn ${methodName(op)}(${signature}) -> Result<${returnType(op)}> {`, () => {
    emitHeaderLocals(w, op);
    emitCall(w, op, callKind(op));
  }, '}');
}

type CallKind = 'json' | 'empty' | 'bytes' | 'multipart' | 'stream';

function callKind(op: Operation): CallKind {
  if (op.body?.encoding === 'multipart') return 'multipart';
  if (!op.response.type) return 'empty';
  if (op.response.type.kind === 'prim' && op.response.type.prim === 'binary') return 'bytes';
  return 'json';
}

/** Build the `headers` vector before the call so optional headers can be skipped. */
function emitHeaderLocals(w: Writer, op: Operation): void {
  if (op.headerParams.length === 0) return;
  w.line("let mut headers: Vec<(&'static str, String)> = Vec::new();");
  for (const header of op.headerParams) {
    const field = rustIdent(snake(header.wire));
    const render = isStringLike(header.type) ? 'clone()' : 'to_string()';
    if (header.required) {
      w.line(`headers.push(("${escape(header.wire)}", params.${field}.${render}));`);
    } else {
      w.block(`if let Some(value) = &params.${field} {`, () => {
        w.line(`headers.push(("${escape(header.wire)}", value.${render}));`);
      }, '}');
    }
  }
}

function emitCall(w: Writer, op: Operation, kind: CallKind): void {
  const query = op.queryParams.length > 0 ? 'Some(params)' : 'NO_QUERY';
  const headers = op.headerParams.length > 0 ? 'headers' : 'Vec::new()';

  if (kind === 'stream') {
    //  Stream options ride on the client clone, not on the call.
    w.line('self.client.request_stream(');
    w.indent(() => {
      w.line(`${pathExprRef(op)},`);
      w.line(`${query},`);
      w.line(`${headers},`);
    });
    w.line(')');
    return;
  }

  if (kind === 'multipart') {
    emitMultipartCall(w, op, query, headers);
    return;
  }

  const method = kind === 'json' ? 'request_json' : kind === 'bytes' ? 'request_bytes' : 'request_empty';
  w.line('self.client');
  w.indent(() => {
    w.line(`.${method}(Request {`);
    w.indent(() => {
      w.line(`method: Method::${op.httpMethod.toUpperCase()},`);
      w.line(`path: ${pathExpr(op)},`);
      w.line(`query: ${query},`);
      w.line(`body: ${op.body ? 'Some(body)' : 'NO_BODY'},`);
      w.line(headers === 'headers' ? 'headers,' : `headers: ${headers},`);
      w.line(`idempotent: ${op.idempotent},`);
    });
    w.line('})');
    w.line('.await');
  });
}

function emitMultipartCall(w: Writer, op: Operation, query: string, headers: string): void {
  const parts = op.body?.parts ?? [];

  w.line('self.client');
  w.indent(() => {
    w.line('.request_multipart(');
    w.indent(() => {
      w.line('Request {');
      w.indent(() => {
        w.line(`method: Method::${op.httpMethod.toUpperCase()},`);
        w.line(`path: ${pathExpr(op)},`);
        w.line(`query: ${query},`);
        w.line('body: NO_BODY,');
        w.line(headers === 'headers' ? 'headers,' : `headers: ${headers},`);
        w.line(`idempotent: ${op.idempotent},`);
      });
      w.line('},');
      w.line('|| {');
      w.indent(() => {
        w.line('let mut form = reqwest::multipart::Form::new();');
        for (const part of parts) {
          const field = rustIdent(snake(part.wire));
          const accessor = `body.${field}`;
          if (part.role === 'file') {
            if (part.required) {
              w.line(`form = form.part("${escape(part.wire)}", ${accessor}.clone().into_part()?);`);
            } else {
              w.block(`if let Some(file) = &${accessor} {`, () => {
                w.line(`form = form.part("${escape(part.wire)}", file.clone().into_part()?);`);
              }, '}');
            }
          } else if (part.required) {
            w.line(`form = form.text("${escape(part.wire)}", field_text(&${accessor})?);`);
          } else {
            w.block(`if let Some(value) = &${accessor} {`, () => {
              w.line(`form = form.text("${escape(part.wire)}", field_text(value)?);`);
            }, '}');
          }
        }
        w.line('Ok(form)');
      });
      w.line('},');
    });
    w.line(')');
    w.line('.await');
  });
}

function emitPaginated(w: Writer, op: Operation, group: Group): void {
  const pagination = op.pagination!;
  const itemType = rustType(pagination.itemType, true);
  const name = paginatedName(op, group);
  const cursorField = rustIdent(snake(pagination.cursorParam));
  const itemsField = rustIdent(snake(pagination.itemsProp));
  const cursorProp = rustIdent(snake(pagination.cursorProp));
  const args = operationArgs(op);
  const signature = ["&'a self", ...args.map((a) => `${a.name}: ${borrowed(a.type)}`)].join(', ');
  const callArgs = args.map((a) => (a.name === 'params' ? '&page_params' : a.name)).join(', ');

  docComment(
    w,
    `Stream every item returned by \`${op.id}\`, following the \`${pagination.cursorProp}\` cursor until the server reports no further pages.`,
  );
  w.block(`pub fn ${name}<'a>(${signature}) -> impl Stream<Item = Result<${itemType}>> + 'a {`, () => {
    w.block('async_stream::try_stream! {', () => {
      w.line('let mut guard = CursorGuard::new();');
      w.line(`let mut cursor = params.${cursorField}.clone();`);
      w.block('loop {', () => {
        w.line('let mut page_params = params.clone();');
        w.line(`page_params.${cursorField} = cursor.clone();`);
        w.line(`let page = self.${methodName(op)}(${callArgs}).await?;`);
        w.line(
          pagination.itemsOptional
            ? `let items = page.${itemsField}.unwrap_or_default();`
            : `let items = page.${itemsField};`,
        );
        w.line('let was_empty = items.is_empty();');
        w.block('for item in items {', () => {
          w.line('yield item;');
        }, '}');
        const hasMore = pagination.hasMoreProp
          ? pagination.hasMoreOptional
            ? `page.${rustIdent(snake(pagination.hasMoreProp))}`
            : `Some(page.${rustIdent(snake(pagination.hasMoreProp))})`
          : 'None';
        w.block(`match guard.advance(page.${cursorProp}, ${hasMore}, was_empty) {`, () => {
          w.line('Some(next) => cursor = Some(next),');
          w.line('None => break,');
        }, '}');
      }, '}');
    }, '}');
  }, '}');
}

function paginatedName(op: Operation, group: Group): string {
  const base = `${methodName(op)}_all`;
  return group.operations.some((other) => methodName(other) === base) ? `${methodName(op)}_auto_paging` : base;
}

/** Auto-paging rewrites the cursor, so it needs an optional `cursor` parameter. */
function canPaginate(op: Operation): boolean {
  if (!op.pagination) return false;
  const cursor = op.queryParams.find((p) => p.wire === op.pagination!.cursorParam);
  return cursor !== undefined && !cursor.required;
}

interface Arg {
  name: string;
  type: string;
}

function operationArgs(op: Operation): Arg[] {
  const args: Arg[] = [];
  for (const param of op.pathParams) {
    args.push({ name: rustIdent(snake(param.wire)), type: argType(param.type) });
  }
  if (op.body) args.push({ name: 'body', type: `&${rustType(op.body.type, true)}` });
  if (paramBag(op).length > 0) args.push({ name: 'params', type: `&${pascal(op.id)}Params` });
  return args;
}

/** `&str` -> `&'a str`, leaving owned types untouched. */
function borrowed(type: string): string {
  return type.startsWith('&') ? `&'a ${type.slice(1)}` : type;
}

/** Path as a `&str` expression, avoiding a needless allocation for literals. */
function pathExprRef(op: Operation): string {
  return op.pathParams.length === 0 ? `"${escape(op.path)}"` : `&${pathExpr(op)}`;
}

function pathExpr(op: Operation): string {
  if (op.pathParams.length === 0) return `"${escape(op.path)}".to_string()`;
  let template = '';
  let rest = op.path;
  const values: string[] = [];
  for (;;) {
    const match = /\{([^}]+)\}/.exec(rest);
    if (!match) {
      template += rest;
      break;
    }
    template += rest.slice(0, match.index) + '{}';
    const param = op.pathParams.find((p) => p.wire === match[1]);
    const name = rustIdent(snake(match[1]!));
    values.push(param && isStringLike(param.type) ? `encode_path(${name})` : `encode_path(&${name}.to_string())`);
    rest = rest.slice(match.index + match[0].length);
  }
  return `format!("${escape(template)}", ${values.join(', ')})`;
}

function methodName(op: Operation): string {
  return rustIdent(snake(op.method));
}

function returnType(op: Operation): string {
  if (!op.response.type) return '()';
  if (op.response.type.kind === 'prim' && op.response.type.prim === 'binary') return 'bytes::Bytes';
  return rustType(op.response.type, true);
}

function paramBag(op: Operation): Param[] {
  return [...op.queryParams, ...op.headerParams];
}

function isStringLike(ref: TypeRef): boolean {
  return ref.kind === 'prim' && ['string', 'uuid', 'uri', 'email', 'date', 'datetime'].includes(ref.prim);
}

/** Argument form: strings are borrowed, models are borrowed, scalars are copied. */
function argType(ref: TypeRef): string {
  const owned = rustType(ref, true);
  if (owned === 'String') return '&str';
  if (owned.startsWith('models::')) return `&${owned}`;
  return owned;
}

export function rustType(ref: TypeRef, qualified: boolean): string {
  switch (ref.kind) {
    case 'named':
      return qualified ? `models::${ref.name}` : ref.name;
    case 'array':
      return `Vec<${rustType(ref.items, qualified)}>`;
    case 'map':
      return `HashMap<String, ${rustType(ref.values, qualified)}>`;
    case 'union':
      // Rust has no structural unions; raw JSON keeps every variant reachable.
      return 'serde_json::Value';
    case 'prim':
      switch (ref.prim) {
        case 'string':
        case 'datetime':
        case 'date':
        case 'uuid':
        case 'uri':
        case 'email':
          return 'String';
        case 'integer':
          return 'i64';
        case 'number':
          return 'f64';
        case 'boolean':
          return 'bool';
        case 'binary':
          return 'FilePart';
        case 'jsonObject':
          return 'serde_json::Map<String, serde_json::Value>';
        default:
          return 'serde_json::Value';
      }
  }
}

function operationDoc(op: Operation): string {
  const parts: string[] = [];
  if (op.summary) parts.push(op.summary);
  if (op.description && op.description !== op.summary) parts.push(op.description);
  parts.push(`\`${op.httpMethod.toUpperCase()} ${op.path}\``);
  if (op.scopes.length > 0) parts.push(`Required scopes: ${op.scopes.map((s) => `\`${s}\``).join(', ')}.`);
  if (op.sse) parts.push('Returns a server-sent event stream.');
  return parts.join('\n\n');
}

function docComment(w: Writer, text: string | undefined): void {
  if (!text) return;
  w.doc(escapeDoc(text), '/// ');
}

/**
 * Defuse the Markdown in a description.
 *
 * Rustdoc renders doc comments as Markdown, which quietly mangles three things
 * the spec's prose is full of. `[...]` becomes an intra-doc link. `<prefix>`
 * parses as an HTML tag and vanishes from the page — the reader is left with
 * `uarp__secret` where the document said `uarp_<prefix>_<secret>`. And a bare
 * URL is rendered as text unless it is wrapped in angle brackets, so links in
 * descriptions are not clickable.
 */
function escapeDoc(text: string): string {
  //  URLs are found first and wrapped, because the escaping below would
  //  otherwise turn the wrapper into literal brackets. Trailing sentence
  //  punctuation is left outside the link: a description almost always ends
  //  `…/keys.`, and swallowing the full stop points the link at a page that
  //  does not exist.
  const url = /https?:\/\/[^\s)>\]]+/g;
  let out = '';
  let last = 0;
  for (const match of text.matchAll(url)) {
    const trimmed = match[0].replace(/[.,;:!?]+$/, '');
    out += escapeMarkdown(text.slice(last, match.index));
    out += `<${trimmed}>`;
    last = match.index + trimmed.length;
  }
  return out + escapeMarkdown(text.slice(last));
}

function escapeMarkdown(text: string): string {
  return text.replace(/[[\]<>]/g, (match) => `\\${match}`);
}

function escape(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

/** `r#type` -> `type`, for comparing against the wire name. */
function stripRaw(name: string): string {
  return name.startsWith('r#') ? name.slice(2) : name;
}
