/** Swift emitter: Codable models plus one `*API` accessor per tag. */
import { sdkVersion, type GeneratedFile } from '../index.ts';
import { assertSupportedBody } from '../ir.ts';
import type { EnumType, Group, ObjectType, Operation, Param, Spec, TypeRef } from '../ir.ts';
import { camel, pascal, swiftIdent } from '../naming.ts';

/** Body encodings this emitter can render. */
const SUPPORTED_BODIES = ['json', 'multipart', 'binary', 'text'] as const;
import { Writer } from '../writer.ts';

const HEADER = '// Code generated by @uarp/codegen from spec/openapi.json. DO NOT EDIT.';
const GENERATED = 'Sources/UARP/Generated';

/** Swift's conventional indentation. */
const SWIFT_INDENT = '    ';

/**
 * Type names that would shadow the standard library or this SDK's own core.
 * The spec really does define a schema called `Error`, and a generated
 * `struct Error` breaks every `throws` signature in the module.
 */
const SHADOWED_TYPE_NAMES = new Set([
  'Error', 'Result', 'Task', 'Optional', 'Array', 'Dictionary', 'Set', 'String', 'Int', 'Double',
  'Float', 'Bool', 'Data', 'Date', 'URL', 'Never', 'Void', 'Any', 'AnyObject', 'Self', 'Type',
  'Codable', 'Decodable', 'Encodable', 'Decoder', 'Encoder', 'Sequence', 'Collection', 'Equatable',
  'Hashable', 'Comparable', 'Identifiable', 'Sendable', 'Character', 'Range', 'Measurement',
  'JSONValue', 'JSONObject', 'FilePart', 'Problem', 'FieldError', 'APIError', 'APIErrorKind',
  'UARPError', 'UARPClient', 'Configuration', 'RequestOptions', 'RequestSpec', 'RequestBody',
  'MultipartPart', 'MultipartValue', 'EventStream', 'ServerEvent', 'StreamOptions', 'SSEParser',
  'Backoff',
]);

/** Model name as it is declared and referenced in Swift. */
function typeName(name: string): string {
  return SHADOWED_TYPE_NAMES.has(name) ? `${name}Model` : name;
}

export function emitSwift(spec: Spec): GeneratedFile[] {
  for (const group of spec.groups) {
    for (const op of group.operations) assertSupportedBody(op, [...SUPPORTED_BODIES]);
  }
  const files: GeneratedFile[] = [];
  files.push({ path: `${GENERATED}/Meta.swift`, content: emitMeta(spec) });
  files.push({ path: `${GENERATED}/Models.swift`, content: emitModels(spec) });
  for (const group of spec.groups) {
    files.push({ path: `${GENERATED}/API/${group.name}API.swift`, content: emitGroup(group) });
  }
  return files;
}

function emitMeta(spec: Spec): string {
  const w = new Writer(SWIFT_INDENT);
  w.line(HEADER);
  w.line();
  w.line('import Foundation');
  w.line();
  w.line('/// Version of the OpenAPI document this SDK was generated from.');
  w.line(`public let specVersion = "${escape(spec.version)}"`);
  w.line();
  w.line('/// Version of this SDK.');
  w.line(`public let sdkVersion = "${escape(sdkVersion())}"`);
  w.line();
  w.line('/// Production base URL.');
  w.line(`public let defaultBaseURL = "${escape(spec.servers[0]?.url ?? 'https://api.snaga.ai')}"`);
  w.line();
  w.line('/// Every scope named by the UARP security scheme.');
  w.line('public let scopes: [String] = [');
  w.indent(() => {
    for (const scope of spec.scopes) w.line(`"${escape(scope)}",`);
  });
  w.line(']');
  return w.toString();
}

// ------------------------------------------------------------------- models

function emitModels(spec: Spec): string {
  const w = new Writer(SWIFT_INDENT);
  w.line(HEADER);
  w.line();
  w.line('import Foundation');
  w.line();

  for (const type of spec.types) {
    if (type.kind === 'enum') emitEnum(w, type);
    else if (type.kind === 'object') emitStruct(w, type);
    else {
      doc(w, type.description);
      w.line(`public typealias ${typeName(type.name)} = ${swiftType(type.target)}`);
    }
    w.line();
  }
  return w.toString();
}

interface Field {
  swift: string;
  wire: string;
  type: string;
  optional: boolean;
  description?: string;
  deprecated?: boolean;
}

function fieldsOf(type: ObjectType): Field[] {
  const used = new Set<string>();
  return type.properties.map((prop) => {
    let name = camel(prop.wire);
    if (name === '' || /^[0-9]/.test(name)) name = `field${pascal(prop.wire)}`;
    while (used.has(name)) name += '_';
    used.add(name);
    return {
      swift: swiftIdent(name),
      wire: prop.wire,
      type: swiftType(prop.type),
      optional: !prop.required || prop.nullable,
      description: prop.description,
      deprecated: prop.deprecated,
    };
  });
}

function emitStruct(w: Writer, type: ObjectType): void {
  const fields = fieldsOf(type);
  const hasExtra = type.additional !== null;

  doc(w, type.description ?? `\`${type.name}\` model.`);
  w.block(`public struct ${typeName(type.name)}: Codable, Hashable, Sendable {`, () => {
    for (const field of fields) {
      // Deprecation is documented rather than annotated: `@available` on a
      // stored property also fires inside this struct's own initialiser.
      const notes = [field.description, field.deprecated ? '- Warning: Deprecated by the API.' : undefined]
        .filter(Boolean)
        .join('\n\n');
      doc(w, notes || undefined);
      w.line(`public var ${field.swift}: ${field.type}${field.optional ? '?' : ''}`);
    }
    if (hasExtra) {
      doc(w, 'Properties the server returned that this SDK does not model.');
      w.line('public var additionalProperties: [String: JSONValue]');
    }
    w.line();

    // Memberwise initialiser: optionals default to nil so call sites stay short.
    const params = fields.map((f) => `${f.swift}: ${f.type}${f.optional ? '? = nil' : ''}`);
    if (hasExtra) params.push('additionalProperties: [String: JSONValue] = [:]');
    if (params.length === 0) {
      w.line('public init() {}');
    } else {
      w.block(`public init(${params.join(', ')}) {`, () => {
        for (const field of fields) w.line(`self.${field.swift} = ${field.swift}`);
        if (hasExtra) w.line('self.additionalProperties = additionalProperties');
      }, '}');
    }

    if (fields.length > 0) {
      w.line();
      w.block('private enum CodingKeys: String, CodingKey {', () => {
        for (const field of fields) w.line(`case ${field.swift} = "${escape(field.wire)}"`);
      }, '}');
    }

    if (hasExtra) emitExtraCoding(w, fields);
  }, '}');
}

/**
 * Types with `additionalProperties` need hand-rolled coding: Swift's synthesized
 * `Codable` drops every key it does not know about.
 */
function emitExtraCoding(w: Writer, fields: Field[]): void {
  w.line();
  w.block('private struct DynamicKey: CodingKey {', () => {
    w.line('let stringValue: String');
    w.line('var intValue: Int? { nil }');
    w.line('init(stringValue: String) { self.stringValue = stringValue }');
    w.line('init?(intValue: Int) { nil }');
  }, '}');
  w.line();
  w.block('public init(from decoder: Decoder) throws {', () => {
    if (fields.length > 0) {
      w.line('let container = try decoder.container(keyedBy: CodingKeys.self)');
      for (const field of fields) {
        w.line(
          field.optional
            ? `self.${field.swift} = try container.decodeIfPresent(${field.type}.self, forKey: .${field.swift})`
            : `self.${field.swift} = try container.decode(${field.type}.self, forKey: .${field.swift})`,
        );
      }
    }
    w.line('let dynamic = try decoder.container(keyedBy: DynamicKey.self)');
    w.line(`let known: Set<String> = [${fields.map((f) => `"${escape(f.wire)}"`).join(', ')}]`);
    w.line('var extra: [String: JSONValue] = [:]');
    w.block('for key in dynamic.allKeys where !known.contains(key.stringValue) {', () => {
      w.line('extra[key.stringValue] = try dynamic.decode(JSONValue.self, forKey: key)');
    }, '}');
    w.line('self.additionalProperties = extra');
  }, '}');
  w.line();
  w.block('public func encode(to encoder: Encoder) throws {', () => {
    if (fields.length > 0) {
      w.line('var container = encoder.container(keyedBy: CodingKeys.self)');
      for (const field of fields) {
        w.line(
          field.optional
            ? `try container.encodeIfPresent(${field.swift}, forKey: .${field.swift})`
            : `try container.encode(${field.swift}, forKey: .${field.swift})`,
        );
      }
    }
    w.line('var dynamic = encoder.container(keyedBy: DynamicKey.self)');
    w.block('for (key, value) in additionalProperties {', () => {
      w.line('try dynamic.encode(value, forKey: DynamicKey(stringValue: key))');
    }, '}');
  }, '}');
}

/**
 * Enums are emitted as `RawRepresentable` structs rather than Swift enums: the
 * API can add a value at any time, and an unknown case must not fail decoding.
 */
function emitEnum(w: Writer, type: EnumType): void {
  const name = typeName(type.name);
  doc(w, type.description ?? `\`${type.name}\` values.`);
  w.line('///');
  w.line('/// Values the API adds later decode into this type unchanged, so a new');
  w.line('/// server-side case never breaks an existing client.');
  w.block(
    `public struct ${name}: RawRepresentable, Codable, Hashable, Sendable, ExpressibleByStringLiteral {`,
    () => {
      w.line('public let rawValue: String');
      w.line('public init(rawValue: String) { self.rawValue = rawValue }');
      w.line('public init(stringLiteral value: String) { self.rawValue = value }');
      w.line('public init(from decoder: Decoder) throws {');
      w.indent(() => w.line('self.rawValue = try decoder.singleValueContainer().decode(String.self)'));
      w.line('}');
      w.line('public func encode(to encoder: Encoder) throws {');
      w.indent(() => {
        w.line('var container = encoder.singleValueContainer()');
        w.line('try container.encode(rawValue)');
      });
      w.line('}');
      w.line();
      const cases = enumCases(type);
      for (const entry of cases) {
        w.line(`public static let ${entry.name} = ${name}(rawValue: "${escape(entry.wire)}")`);
      }
      w.line();
      w.line('/// Every value the spec declared at generation time.');
      w.line(`public static let knownValues: [${name}] = [${cases.map((c) => `.${c.name}`).join(', ')}]`);
    },
    '}',
  );
}

interface EnumCase {
  name: string;
  wire: string;
}

function enumCases(type: EnumType): EnumCase[] {
  const used = new Set<string>();
  const out: EnumCase[] = [];
  for (const value of type.values) {
    let name = camel(value) || 'empty';
    if (/^[0-9]/.test(name)) name = `v${name}`;
    while (used.has(name)) name += '_';
    used.add(name);
    out.push({ name: swiftIdent(name), wire: value });
  }
  return out;
}

// ---------------------------------------------------------------------- api

function emitGroup(group: Group): string {
  const w = new Writer(SWIFT_INDENT);
  w.line(HEADER);
  w.line();
  w.line('import Foundation');
  w.line();

  doc(w, group.description ?? `Operations tagged \`${group.tag}\`.`);
  w.block(`public struct ${group.name}API: Sendable {`, () => {
    w.line('let client: UARPClient');
    w.line();
    w.line('init(client: UARPClient) { self.client = client }');
    for (const op of group.operations) {
      w.line();
      emitOperation(w, op);
      if (op.pagination) {
        w.line();
        emitPaginated(w, op, group);
      }
    }
  }, '}');
  w.line();
  w.block('extension UARPClient {', () => {
    doc(w, group.description ?? `Operations tagged \`${group.tag}\`.`);
    w.line(`public var ${swiftIdent(camel(group.accessor))}: ${group.name}API { ${group.name}API(client: self) }`);
  }, '}');
  return w.toString();
}

interface Arg {
  label: string;
  type: string;
  optional: boolean;
}

function operationArgs(op: Operation): Arg[] {
  const args: Arg[] = [];
  const used = new Set<string>();
  const unique = (name: string): string => {
    let candidate = name;
    while (used.has(candidate)) candidate += '_';
    used.add(candidate);
    return candidate;
  };

  for (const param of op.pathParams) {
    args.push({ label: swiftIdent(unique(camel(param.wire))), type: swiftType(param.type), optional: false });
  }
  if (op.body) {
    args.push({ label: swiftIdent(unique('body')), type: bodyType(op), optional: !op.body.required });
  }
  for (const param of [...op.queryParams, ...op.headerParams]) {
    args.push({
      label: swiftIdent(unique(camel(param.wire))),
      type: swiftType(param.type),
      optional: !param.required,
    });
  }
  return args;
}

function emitOperation(w: Writer, op: Operation): void {
  const args = operationArgs(op);
  const signature = [
    ...args.map((a) => `${a.label}: ${a.type}${a.optional ? '? = nil' : ''}`),
    'options: RequestOptions = .init()',
  ].join(', ');

  doc(w, operationDoc(op));
  if (op.deprecated) w.line('@available(*, deprecated)');

  if (op.sse) {
    w.block(`public func ${methodName(op)}(${signature}) -> EventStream {`, () => {
      emitSpec(w, op, args, 'stream');
    }, '}');
    return;
  }

  const kind = callKind(op);
  const returns = kind === 'void' ? '' : ` -> ${returnType(op)}`;
  w.block(`public func ${methodName(op)}(${signature}) async throws${returns} {`, () => {
    emitSpec(w, op, args, kind);
  }, '}');
}

type CallKind = 'json' | 'void' | 'data' | 'stream';

function callKind(op: Operation): CallKind {
  if (!op.response.type) return 'void';
  if (op.response.type.kind === 'prim' && op.response.type.prim === 'binary') return 'data';
  return 'json';
}

function emitSpec(w: Writer, op: Operation, args: Arg[], kind: CallKind): void {
  const argOf = (wire: string, offset: number): string => args[offset]!.label;

  if (op.queryParams.length > 0) {
    w.line('var query: [URLQueryItem] = []');
    for (const param of op.queryParams) {
      const label = labelFor(op, args, param);
      appendQuery(w, param, label);
    }
  }
  if (op.headerParams.length > 0) {
    w.line('var headers: [String: String] = [:]');
    for (const param of op.headerParams) {
      const label = labelFor(op, args, param);
      if (param.required) {
        w.line(`headers["${escape(param.wire)}"] = ${queryValue(param.type, label)}`);
      } else {
        w.block(`if let ${label} {`, () => {
          w.line(`headers["${escape(param.wire)}"] = ${queryValue(param.type, label)}`);
        }, '}');
      }
    }
  }
  if (op.body?.encoding === 'multipart') emitMultipart(w, op, args);
  if (op.body && op.body.encoding === 'json' && !op.body.required) {
    const label = args[op.pathParams.length]!.label;
    w.line(`let encodedBody: RequestBody? = try ${label}.map { try client.encode($0) }`);
  }

  const specLines: string[] = [
    `method: "${op.httpMethod.toUpperCase()}"`,
    `path: ${pathExpr(op, args)}`,
  ];
  if (op.queryParams.length > 0) specLines.push('query: query');
  if (op.headerParams.length > 0) specLines.push('headers: headers');
  if (op.body) specLines.push(`body: ${bodyExpr(op, args)}`);
  if (op.idempotent) specLines.push('idempotent: true');
  specLines.push('options: options');

  const call =
    kind === 'stream'
      ? 'client.sendStream'
      : kind === 'void'
        ? 'try await client.sendVoid'
        : kind === 'data'
          ? 'try await client.sendData'
          : 'try await client.send';

  // Multi-statement bodies need an explicit `return`.
  const prefix = kind === 'void' ? '' : 'return ';
  w.line(`${prefix}${call}(RequestSpec(`);
  w.indent(() => {
    for (const [index, line] of specLines.entries()) {
      w.line(index === specLines.length - 1 ? line : `${line},`);
    }
  });
  w.line('))');
  void argOf;
}

function labelFor(op: Operation, args: Arg[], param: Param): string {
  const offset =
    op.pathParams.length + (op.body ? 1 : 0) + [...op.queryParams, ...op.headerParams].indexOf(param);
  return args[offset]!.label;
}

function appendQuery(w: Writer, param: Param, label: string): void {
  const value = queryValue(param.type, label);
  if (param.required) {
    w.line(`query.append(URLQueryItem(name: "${escape(param.wire)}", value: ${value}))`);
  } else {
    w.block(`if let ${label} {`, () => {
      w.line(`query.append(URLQueryItem(name: "${escape(param.wire)}", value: ${value}))`);
    }, '}');
  }
}

/** Render a parameter as a query/header string. */
function queryValue(ref: TypeRef, label: string): string {
  if (ref.kind === 'named') return `${label}.rawValue`;
  if (ref.kind === 'prim') {
    switch (ref.prim) {
      case 'integer':
      case 'number':
      case 'boolean':
        return `String(${label})`;
      case 'string':
      case 'uuid':
      case 'uri':
      case 'email':
      case 'date':
      case 'datetime':
        return label;
      default:
        return `String(describing: ${label})`;
    }
  }
  return `String(describing: ${label})`;
}

function emitMultipart(w: Writer, op: Operation, args: Arg[]): void {
  const bodyLabel = args[op.pathParams.length]!.label;
  w.line('var parts: [MultipartPart] = []');
  for (const part of op.body?.parts ?? []) {
    const accessor = `${bodyLabel}.${swiftIdent(camel(part.wire))}`;
    const value = part.role === 'file' ? '.file(value)' : '.text(value)';
    if (part.required) {
      w.line(`parts.append(MultipartPart(name: "${escape(part.wire)}", value: ${part.role === 'file' ? `.file(${accessor})` : `.text(${accessor})`}))`);
    } else {
      w.block(`if let value = ${accessor} {`, () => {
        w.line(`parts.append(MultipartPart(name: "${escape(part.wire)}", value: ${value}))`);
      }, '}');
    }
  }
}

function bodyExpr(op: Operation, args: Arg[]): string {
  const body = op.body!;
  const label = args[op.pathParams.length]!.label;
  if (body.encoding === 'multipart') return '.multipart(parts)';
  if (body.encoding === 'binary') return `.raw(${label}, contentType: "application/octet-stream")`;
  if (body.encoding === 'text') return `.raw(Data(${label}.utf8), contentType: "text/plain")`;
  return body.required ? `try client.encode(${label})` : 'encodedBody';
}

function emitPaginated(w: Writer, op: Operation, group: Group): void {
  const pagination = op.pagination!;
  const args = operationArgs(op);
  const itemType = swiftType(pagination.itemType);
  const name = paginatedName(op, group);
  const cursorArg = args[
    op.pathParams.length +
      (op.body ? 1 : 0) +
      [...op.queryParams, ...op.headerParams].findIndex((p) => p.wire === pagination.cursorParam)
  ]!.label;

  const signature = [
    ...args.map((a) => `${a.label}: ${a.type}${a.optional ? '? = nil' : ''}`),
    'options: RequestOptions = .init()',
  ].join(', ');
  const callArgs = args.map((a) => (a.label === cursorArg ? `${a.label}: cursor` : `${a.label}: ${a.label}`));

  doc(
    w,
    `Stream every item returned by \`${op.id}\`, following the \`${pagination.cursorProp}\` cursor until the server reports no further pages.`,
  );
  w.block(`public func ${name}(${signature}) -> AsyncThrowingStream<${itemType}, Error> {`, () => {
    w.line('autoPaginate(');
    w.indent(() => {
      w.line(`fetch: { cursor in try await self.${methodName(op)}(${[...callArgs, 'options: options'].join(', ')}) },`);
      w.line(
        pagination.itemsOptional
          ? `items: { $0.${camel(pagination.itemsProp)} ?? [] },`
          : `items: { $0.${camel(pagination.itemsProp)} },`,
      );
      w.line(`cursor: { $0.${camel(pagination.cursorProp)} },`);
      w.line(pagination.hasMoreProp ? `hasMore: { $0.${camel(pagination.hasMoreProp)} }` : 'hasMore: { _ in nil }');
    });
    w.line(')');
  }, '}');
}

function paginatedName(op: Operation, group: Group): string {
  const base = `${methodName(op)}All`;
  return group.operations.some((other) => methodName(other) === base) ? `${methodName(op)}AutoPaging` : base;
}

function pathExpr(op: Operation, args: Arg[]): string {
  if (op.pathParams.length === 0) return `"${escape(op.path)}"`;
  let out = '"';
  let rest = op.path;
  for (;;) {
    const match = /\{([^}]+)\}/.exec(rest);
    if (!match) {
      out += escape(rest);
      break;
    }
    out += escape(rest.slice(0, match.index));
    const index = op.pathParams.findIndex((p) => p.wire === match[1]);
    const arg = args[index]!;
    const value = arg.type === 'String' ? arg.label : `String(describing: ${arg.label})`;
    out += `\\(encodePathSegment(${value}))`;
    rest = rest.slice(match.index + match[0].length);
  }
  return out + '"';
}

function methodName(op: Operation): string {
  return swiftIdent(camel(op.method));
}

function bodyType(op: Operation): string {
  const body = op.body!;
  if (body.encoding === 'binary') return 'Data';
  if (body.encoding === 'text') return 'String';
  return swiftType(body.type);
}

function returnType(op: Operation): string {
  if (!op.response.type) return 'Void';
  if (op.response.type.kind === 'prim' && op.response.type.prim === 'binary') return 'Data';
  return swiftType(op.response.type);
}

export function swiftType(ref: TypeRef): string {
  switch (ref.kind) {
    case 'named':
      return typeName(ref.name);
    case 'array':
      return `[${swiftType(ref.items)}]`;
    case 'map':
      return `[String: ${swiftType(ref.values)}]`;
    case 'union':
      // Swift has no structural unions; raw JSON keeps every variant reachable.
      return 'JSONValue';
    case 'prim':
      switch (ref.prim) {
        case 'string':
        case 'datetime':
        case 'date':
        case 'uuid':
        case 'uri':
        case 'email':
          return 'String';
        case 'integer':
          return 'Int';
        case 'number':
          return 'Double';
        case 'boolean':
          return 'Bool';
        case 'binary':
          return 'FilePart';
        case 'jsonObject':
          return 'JSONObject';
        default:
          return 'JSONValue';
      }
  }
}

function operationDoc(op: Operation): string {
  const parts: string[] = [];
  if (op.summary) parts.push(op.summary);
  if (op.description && op.description !== op.summary) parts.push(op.description);
  parts.push(`\`${op.httpMethod.toUpperCase()} ${op.path}\``);
  if (op.scopes.length > 0) parts.push(`Required scopes: ${op.scopes.map((s) => `\`${s}\``).join(', ')}.`);
  if (op.sse) parts.push('Returns a server-sent event stream; iterate it with `for try await`.');
  return parts.join('\n\n');
}

function doc(w: Writer, text: string | undefined): void {
  if (!text) return;
  w.doc(text, '/// ');
}

function escape(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\(/g, '(');
}
