/** TypeScript emitter: models + one resource class per tag. */
import { sdkVersion, type GeneratedFile } from '../index.ts';
import { assertSupportedBody } from '../ir.ts';
import type { Group, NamedType, Operation, Param, Spec, TypeRef } from '../ir.ts';
import { camel, isPlainJsKey, kebab, pascal, tsIdent } from '../naming.ts';

/** Body encodings this emitter can render. */
const SUPPORTED_BODIES = ['json', 'multipart', 'binary', 'form', 'text'] as const;
import { Writer } from '../writer.ts';

const HEADER = `// Code generated by @uarp/codegen from spec/openapi.json. DO NOT EDIT.`;

export function emitTypeScript(spec: Spec): GeneratedFile[] {
  for (const group of spec.groups) {
    for (const op of group.operations) assertSupportedBody(op, [...SUPPORTED_BODIES]);
  }
  const files: GeneratedFile[] = [];
  files.push({ path: 'src/generated/models.ts', content: emitModels(spec) });
  for (const group of spec.groups) {
    files.push({ path: `src/generated/resources/${kebab(group.name)}.ts`, content: emitResource(group) });
  }
  files.push({ path: 'src/generated/resources/index.ts', content: emitResourceIndex(spec) });
  files.push({ path: 'src/generated/meta.ts', content: emitMeta(spec) });
  return files;
}

// ------------------------------------------------------------------- models

function emitModels(spec: Spec): string {
  const w = new Writer();
  w.line(HEADER);
  w.line();
  w.doc(
    'Data models for the ' + spec.title + ' API (spec version ' + spec.version + ').',
    ' * ',
    '/**',
    ' */',
  );
  w.line("import type { BinaryInput, JsonObject, JsonValue } from '../core/json.js';");
  w.line();
  w.line('export type { BinaryInput, JsonObject, JsonValue };');
  w.line();

  for (const type of spec.types) {
    emitType(w, type);
    w.line();
  }
  return w.toString();
}

// A star-slash sequence inside a description would close the JSDoc block early.
function safeDoc(text: string | undefined): string | undefined {
  return text?.replace(/\*\//g, '*&#47;');
}

function emitType(w: Writer, type: NamedType): void {
  w.doc(safeDoc(type.description), ' * ', '/**', ' */');
  if (type.kind === 'enum') {
    w.line(`export type ${type.name} = ${type.values.map((v) => `'${escapeString(v)}'`).join(' | ')};`);
    w.line();
    w.line(`export const ${constName(type.name)} = [${type.values.map((v) => `'${escapeString(v)}'`).join(', ')}] as const;`);
    return;
  }
  if (type.kind === 'alias') {
    w.line(`export type ${type.name} = ${tsType(type.target)};`);
    return;
  }
  w.block(`export interface ${type.name} {`, () => {
    for (const prop of type.properties) {
      const docs: string[] = [];
      if (prop.description) docs.push(prop.description);
      if (prop.deprecated) docs.push('@deprecated');
      if (prop.defaultValue !== undefined) docs.push(`@default ${JSON.stringify(prop.defaultValue)}`);
      w.doc(safeDoc(docs.join('\n\n')), ' * ', '/**', ' */');
      const key = isPlainJsKey(prop.wire) ? prop.wire : `'${escapeString(prop.wire)}'`;
      const base = prop.constValue !== undefined ? `'${escapeString(prop.constValue)}'` : tsType(prop.type);
      const value = prop.nullable ? `${base} | null` : base;
      w.line(`${key}${prop.required ? '' : '?'}: ${value};`);
    }
    if (type.additional) {
      // `unknown` rather than the declared additional type: an index signature has
      // to accept every declared property, including the optional ones.
      w.doc(
        `Additional free-form properties (\`${tsType(type.additional)}\` on the wire).`,
        ' * ',
        '/**',
        ' */',
      );
      w.line('[key: string]: unknown;');
    }
  }, '}');
}

function constName(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase() + '_VALUES';
}

// ---------------------------------------------------------------- resources

function emitResource(group: Group): string {
  const w = new Writer();
  const used = collectTypeNames(group);

  const needsPick = group.operations.some((o) => paramBag(o).length > 0);
  const needsStream = group.operations.some((o) => o.sse);
  const needsPaging = group.operations.some((o) => o.pagination);

  w.line(HEADER);
  w.line();
  w.line("import { APIResource } from '../../core/resource.js';");
  w.line("import type { RequestOptions } from '../../core/transport.js';");
  if (needsPick) w.line("import { pick } from '../../core/util.js';");
  if (needsStream) w.line("import type { EventStream } from '../../core/sse.js';");
  if (needsPaging) w.line("import { autoPaginate } from '../../core/pagination.js';");
  if (used.size > 0) {
    w.line(`import type {`);
    w.indent(() => {
      for (const name of [...used].sort()) w.line(`${name},`);
    });
    w.line(`} from '../models.js';`);
  }
  w.line();

  // Per-operation params interfaces.
  for (const op of group.operations) {
    const params = paramBag(op);
    if (params.length === 0) continue;
    w.doc(`Query and header parameters for \`${op.id}\`.`, ' * ', '/**', ' */');
    w.block(`export interface ${pascal(op.id)}Params {`, () => {
      for (const p of params) {
        w.doc(safeDoc(p.description), ' * ', '/**', ' */');
        const key = isPlainJsKey(p.wire) ? p.wire : `'${escapeString(p.wire)}'`;
        w.line(`${key}${p.required ? '' : '?'}: ${tsType(p.type)};`);
      }
    }, '}');
    w.line();
  }

  w.doc(safeDoc(group.description ?? `Operations tagged \`${group.tag}\`.`), ' * ', '/**', ' */');
  w.block(`export class ${group.name}Resource extends APIResource {`, () => {
    let first = true;
    for (const op of group.operations) {
      if (!first) w.line();
      first = false;
      emitOperation(w, op);
      if (op.pagination) {
        w.line();
        emitAutoPaging(w, op, group);
      }
    }
  }, '}');
  return w.toString();
}

interface Arg {
  name: string;
  type: string;
  optional: boolean;
}

/** Path parameters become bindings, so a name like `default` must be escaped. */
function argName(wire: string): string {
  return tsIdent(camel(wire));
}

function operationArgs(op: Operation): Arg[] {
  const args: Arg[] = [];
  for (const p of op.pathParams) {
    args.push({ name: argName(p.wire), type: tsType(p.type), optional: false });
  }
  if (op.body) {
    args.push({ name: 'body', type: bodyType(op), optional: !op.body.required });
  }
  const params = paramBag(op);
  if (params.length > 0) {
    args.push({
      name: 'params',
      type: `${pascal(op.id)}Params`,
      optional: params.every((p) => !p.required),
    });
  }
  args.push({ name: 'options', type: 'RequestOptions', optional: true });
  return args;
}

function renderArgs(args: Arg[]): string {
  return args
    .map((arg, i) => {
      const laterRequired = args.slice(i + 1).some((a) => !a.optional);
      if (!arg.optional) return `${arg.name}: ${arg.type}`;
      return laterRequired ? `${arg.name}: ${arg.type} | undefined` : `${arg.name}?: ${arg.type}`;
    })
    .join(', ');
}

function emitOperation(w: Writer, op: Operation): void {
  const args = operationArgs(op);
  const returns = op.sse ? 'EventStream' : `Promise<${responseType(op)}>`;

  w.doc(safeDoc(operationDoc(op)), ' * ', '/**', ' */');
  w.block(`${op.method}(${renderArgs(args)}): ${returns} {`, () => {
    emitRequestCall(w, op, op.sse ? 'stream' : 'request');
  }, '}');
}

function emitAutoPaging(w: Writer, op: Operation, group: Group): void {
  const pagination = op.pagination!;
  const args = operationArgs(op).filter((a) => a.name !== 'options');
  const itemType = tsType(pagination.itemType);
  const name = autoPagingName(op, group);
  const callArgs = args.map((a) => a.name);

  w.doc(
    `Iterate every item returned by \`${op.id}\`, following the \`${pagination.cursorProp}\` cursor until the server reports no further pages.`,
    ' * ',
    '/**',
    ' */',
  );
  const sig = renderArgs([...args, { name: 'options', type: 'RequestOptions', optional: true }]);
  w.block(`${name}(${sig}): AsyncIterableIterator<${itemType}> {`, () => {
    const paramsArg = args.some((a) => a.name === 'params') ? 'params' : 'undefined';
    w.line(`return autoPaginate<${itemType}>(`);
    w.indent(() => {
      w.line(`(cursor) => this.${op.method}(${patchCursor(callArgs, paramsArg)}, options),`);
      w.line(`'${pagination.itemsProp}',`);
      w.line(`'${pagination.cursorProp}',`);
      w.line(pagination.hasMoreProp ? `'${pagination.hasMoreProp}',` : 'undefined,');
    });
    w.line(');');
  }, '}');
}

/**
 * Rewrite the argument list so each iteration passes the next cursor. A
 * paginated operation always has a `cursor` query parameter, so the params
 * argument is guaranteed to exist and to accept the override.
 */
function patchCursor(callArgs: string[], paramsArg: string): string {
  const patched = `{ ...params, cursor }`;
  if (paramsArg === 'undefined') return [...callArgs, patched].join(', ');
  return callArgs.map((a) => (a === 'params' ? patched : a)).join(', ');
}

function autoPagingName(op: Operation, group: Group): string {
  const candidate = `${op.method}All`;
  const taken = group.operations.some((o) => o.method === candidate);
  return taken ? `${op.method}AutoPaging` : candidate;
}

function emitRequestCall(w: Writer, op: Operation, kind: 'request' | 'stream'): void {
  const pathExpr = pathTemplate(op);
  const query = op.queryParams;
  const headers = op.headerParams;

  w.line(`return this._client.${kind}({`);
  w.indent(() => {
    w.line(`method: '${op.httpMethod.toUpperCase()}',`);
    w.line(`path: ${pathExpr},`);
    if (query.length > 0) {
      w.line(`query: ${pickExpr('params', query)},`);
    }
    if (headers.length > 0) {
      w.line(`headers: ${pickExpr('params', headers)},`);
    }
    if (op.body) {
      if (op.body.encoding === 'multipart') w.line('multipart: body,');
      else if (op.body.encoding === 'binary') w.line('binary: body,');
      else if (op.body.encoding === 'form') w.line('form: body,');
      else w.line('body,');
    }
    if (op.idempotent) w.line('idempotent: true,');
    if (kind === 'request' && op.response.type?.kind === 'prim' && op.response.type.prim === 'binary') {
      w.line("responseType: 'binary',");
    } else if (kind === 'request' && !op.response.type) {
      w.line("responseType: 'void',");
    }
    w.line('options,');
  });
  w.line('});');
}

/** `pick(params, ['limit','cursor'])` keeps undefined values out of the request. */
function pickExpr(source: string, params: Param[]): string {
  const keys = params.map((p) => `'${escapeString(p.wire)}'`).join(', ');
  return `pick(${source}, [${keys}])`;
}

function pathTemplate(op: Operation): string {
  if (op.pathParams.length === 0) return `'${escapeString(op.path)}'`;
  let out = '`';
  let rest = op.path;
  for (;;) {
    const match = /\{([^}]+)\}/.exec(rest);
    if (!match) {
      out += escapeTemplate(rest);
      break;
    }
    out += escapeTemplate(rest.slice(0, match.index));
    out += '${encodeURIComponent(String(' + argName(match[1]!) + '))}';
    rest = rest.slice(match.index + match[0].length);
  }
  return out + '`';
}

function emitResourceIndex(spec: Spec): string {
  const w = new Writer();
  w.line(HEADER);
  w.line();
  w.line("import type { Transport } from '../../core/transport.js';");
  for (const group of spec.groups) {
    w.line(`import { ${group.name}Resource } from './${kebab(group.name)}.js';`);
  }
  w.line();
  // Re-export the resource classes together with their `*Params` interfaces.
  for (const group of spec.groups) {
    w.line(`export * from './${kebab(group.name)}.js';`);
  }
  w.line();
  w.doc('Every resource group exposed on the client, keyed by its accessor name.', ' * ', '/**', ' */');
  w.block('export interface Resources {', () => {
    for (const group of spec.groups) {
      w.doc(safeDoc(group.description), ' * ', '/**', ' */');
      w.line(`readonly ${group.accessor}: ${group.name}Resource;`);
    }
  }, '}');
  w.line();
  w.block('export function createResources(client: Transport): Resources {', () => {
    w.block('return {', () => {
      for (const group of spec.groups) {
        w.line(`${group.accessor}: new ${group.name}Resource(client),`);
      }
    }, '};');
  }, '}');
  return w.toString();
}

function emitMeta(spec: Spec): string {
  const w = new Writer();
  w.line(HEADER);
  w.line();
  w.line(`export const SPEC_VERSION = '${escapeString(spec.version)}';`);
  w.line();
  w.doc('Version of this SDK.', ' * ', '/**', ' */');
  w.line(`export const SDK_VERSION = '${escapeString(sdkVersion())}';`);
  w.line(`export const DEFAULT_BASE_URL = '${escapeString(spec.servers[0]?.url ?? 'https://api.snaga.ai')}';`);
  w.line();
  w.doc('Every scope named by the UARP security scheme.', ' * ', '/**', ' */');
  w.line(`export const SCOPES = [${spec.scopes.map((s) => `'${escapeString(s)}'`).join(', ')}] as const;`);
  w.line();
  w.line('export type Scope = (typeof SCOPES)[number];');
  return w.toString();
}

// ------------------------------------------------------------------- shared

function paramBag(op: Operation): Param[] {
  return [...op.queryParams, ...op.headerParams];
}

function bodyType(op: Operation): string {
  const body = op.body!;
  if (body.encoding === 'binary') return 'BinaryInput';
  if (body.encoding === 'text') return 'string';
  return tsType(body.type);
}

function responseType(op: Operation): string {
  if (!op.response.type) return 'void';
  if (op.response.type.kind === 'prim' && op.response.type.prim === 'binary') return 'Blob';
  return tsType(op.response.type);
}

function operationDoc(op: Operation): string {
  const parts: string[] = [];
  if (op.summary) parts.push(op.summary);
  if (op.description && op.description !== op.summary) parts.push(op.description);
  parts.push(`\`${op.httpMethod.toUpperCase()} ${op.path}\``);
  if (op.scopes.length > 0) parts.push(`Required scopes: ${op.scopes.map((s) => `\`${s}\``).join(', ')}.`);
  if (op.sse) parts.push('Returns a server-sent event stream; iterate it with `for await`.');
  if (op.deprecated) parts.push('@deprecated');
  return parts.join('\n\n');
}

export function tsType(ref: TypeRef): string {
  switch (ref.kind) {
    case 'named':
      return ref.name;
    case 'array': {
      const inner = tsType(ref.items);
      return /[|&]/.test(inner) ? `Array<${inner}>` : `${inner}[]`;
    }
    case 'map':
      return `Record<string, ${tsType(ref.values)}>`;
    case 'union':
      return ref.variants.map(tsType).join(' | ');
    case 'prim':
      switch (ref.prim) {
        case 'string':
        case 'datetime':
        case 'date':
        case 'uuid':
        case 'uri':
        case 'email':
          return 'string';
        case 'integer':
        case 'number':
          return 'number';
        case 'boolean':
          return 'boolean';
        case 'binary':
          return 'BinaryInput';
        case 'jsonObject':
          return 'JsonObject';
        default:
          return 'JsonValue';
      }
  }
}

function collectTypeNames(group: Group): Set<string> {
  const names = new Set<string>();
  const visit = (ref: TypeRef | undefined): void => {
    if (!ref) return;
    switch (ref.kind) {
      case 'named':
        names.add(ref.name);
        return;
      case 'array':
        return visit(ref.items);
      case 'map':
        return visit(ref.values);
      case 'union':
        ref.variants.forEach(visit);
        return;
      case 'prim':
        if (ref.prim === 'binary') names.add('BinaryInput');
        if (ref.prim === 'jsonObject') names.add('JsonObject');
        if (ref.prim === 'json') names.add('JsonValue');
    }
  };
  for (const op of group.operations) {
    for (const p of [...op.pathParams, ...op.queryParams, ...op.headerParams]) visit(p.type);
    if (op.body) visit(op.body.type);
    if (!op.sse && !(op.response.type?.kind === 'prim' && op.response.type.prim === 'binary')) visit(op.response.type);
    if (op.pagination) visit(op.pagination.itemType);
  }
  return names;
}

function escapeString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}

function escapeTemplate(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}
